mercedes-benz/sechub

- docs/_config.yml
Oliver Kopp <oliver.kopp@daimler.com>, Daimler AG on behalf of Daimler TSS GmbH.
[Imprint](https://www.daimler-tss.com/en/imprint/)
License: MIT
> Change theme to Daimler TSS GmbH's slate theme

- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java
* increment count variable to avoid infinite loop
* finding based on [lgtms' report](https://lgtm.com/projects/g/Daimler/sechub/snapshot/91c873adb7b33b1313458e3971ff157c16557bb2/files/sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java?sort=name&dir=ASC&mode=heatmap#x14203afd56f501c6:1) for this project
> Avoid infinite loop while waiting for job report

- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectAssignUserService.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectCreationService.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectDeleteService.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectTransactionService.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectUnassignUserService.java
- sechub-administration/src/test/java/com/daimler/sechub/domain/administration/project/ProjectDeleteServiceTest.java
- providing special ProjectTransactionService for transaction
parts with own transaction
- changeded former direct calls to repository by other services to
calls to transaction service
- updated junit tests
> Handle race conditions on role recalculation #120

- sechub-cli/build_go.sh
New platforms:
- "linux/amd64" Linux default architecture
- "linux/arm" Raspberry PI
- "linux/arm64" Raspberry PI/Amazon
- "darwin/amd64" Mac
> Feature 167 added popular build platforms

- sechub-cli/build_go.sh
..by adding -ldflags="-s -w"
Successfully verified.
>  feature-173 Strip SecHub Go client binaries

- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/priviledges/RevokeAdminRightsFromAdminAction.java
- optimized menu structure
- fixed typo
> Improved menu structure, closes #183

- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/DialogUI.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/ThreeButtonDialogResult.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/ThreeButtonDialogUI.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/AbstractUIAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/CreateProjectAction.java
- added a new ThreeButtonDialog
- added a ThreeButtonDialogResult class to store return values from the ThreeButtonDialog
- uses ThreeButton dialog in create project action to be able to add more URLs to the whitelist
- pressing the cancel button on the description field now terminates the project creation, as expected
> Feature 158 provide 3 button confirmation admin ui

- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/AssignUserToProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/CreateProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/DeleteProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/GetProjectMockConfigurationAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/SetProjectMockDataConfigurationAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/ShowProjectDetailAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/ShowProjectsScanLogsAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/UnassignUserFromProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/UpdateProjectWhitelistAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/AcceptUserSignupAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/AnonymousRequestNewAPITokenUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/DeleteUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/ShowUserDetailAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/priviledges/GrantAdminRightsToUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/priviledges/RevokeAdminRightsFromAdminAction.java
All changes are locally verified
Closes #199
> Feature 199 AdminUI fix case sensitivity

- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/DeveloperAdministration.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/integrationtestserver/IntegrationTestAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/job/CancelJobAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/AssignUserToProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/CreateProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/SetProjectMockDataConfigurationAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/UnassignUserFromProjectAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/UpdateProjectWhitelistAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/scheduler/DisableSchedulerJobProcessingAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/scheduler/EnableSchedulerJobProcessingAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/AcceptUserSignupAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/AnonymousRequestNewAPITokenUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/AnonymousSigninNewUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/DeleteUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/priviledges/GrantAdminRightsToUserAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/user/priviledges/RevokeAdminRightsFromAdminAction.java
Added extra confirmation dialogs to all update, create and delete actions in the developer UI, which did not previously had it.
> Feature 157 developer admin ui are you sure

- docs/index.md
- sechub-doc/build.gradle
- sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
Added the quickstart guide to SecHub.
> Feature 153 Quickstart Guide

- .github/workflows/gradle.yml
- continous-integration-multibranch-pipeline.jenkins
- sechub-cli/src/daimler.com/sechub/cli/config.go
- sechub-cli/src/daimler.com/sechub/cli/help.go
- sechub-developertools/client-test/README.md
- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- providing environment variables for username, server and api token
- adapt documentation
- fixed github action build issue
> Feature 36 go client supports env variables #36

- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AssertMail.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AssertUser.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/MockEmailAccess.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario2/SwitchSchedulerJobProcessingScenario2IntTest.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario2/UserAdministrationScenario2IntTest.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/NotificationMessageHandler.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/owner/InformOwnerThatProjectHasBeenDeletedNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/superadmin/InformAdminsThatProjectHasBeenDeletedNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/superadmin/InformAdminsThatSchedulerJobProcessingHasBeenDisabledService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/superadmin/InformAdminsThatSchedulerJobProcessingHasBeenEnabledService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/superadmin/InformAdminsThatUserBecomesAdminNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/superadmin/InformAdminsThatUserNoLongerAdminNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/InformUserThatJobHasBeenCanceledService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/InformUserThatUserBecomesAdminNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/InformUserThatUserNoLongerAdminNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/InformUsersThatProjectHasBeenDeletedNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/NewAPITokenAppliedUserNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/SignUpRequestedAdminNotificationService.java
- sechub-notification/src/main/java/com/daimler/sechub/domain/notification/user/UserDeletedNotificationService.java
- sechub-notification/src/test/java/com/daimler/sechub/domain/notification/NotificationMessageHandlerTest.java
- sechub-notification/src/test/java/com/daimler/sechub/domain/notification/owner/InformOwnerThatProjectHasBeenDeletedNotificationServiceTest.java
- sechub-notification/src/test/java/com/daimler/sechub/domain/notification/user/InformUsersThatProjectHasBeenDeletedNotificationServiceTest.java
- sechub-notification/src/test/java/com/daimler/sechub/domain/notification/user/SignUpRequestedAdminNotificationServiceTest.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/Profiles.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/SecHubEnvironment.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/UseCaseGroup.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/user/UseCaseAdministratorListsAllAdmins.java
- sechub-test/src/test/java/com/daimler/sechub/test/RequestMappingForAdminAPImarkedWithAdminAccessProfileTest.java
Improved email texts and fixed some typos:
- tweaked email texts and subjects
- added environment url where possible
- spell corrections
- tested+verified locally
- builds are green
---
> Feature 164 fix texts in admin mails (#244)

- sechub-cli/src/daimler.com/sechub/cli/config.go
> remove trailing / in server url #233

- sechub-doc/src/docs/asciidoc/documents/code2doc/usecases/user/unmark_false_positives.adoc
- sechub-doc/src/test/java/com/daimler/sechub/restdoc/FalsePositiveRestControllerRestDocTest.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AssertSecHubReport.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/TestRestHelper.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario3/FalsePositivesScenario3IntTest.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/project/FalsePositiveJobDataConfigMerger.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/project/FalsePositiveJobDataService.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/project/FalsePositiveRestController.java
- sechub-scan/src/test/java/com/daimler/sechub/domain/scan/project/FalsePositiveJobDataConfigMergerTest.java
- sechub-scan/src/test/resources/sechub_result/sechub-report-example1-noscantype.json
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/UseCaseIdentifier.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/user/execute/UseCaseUserUnmarksFalsePositives.java
- sechub-testframework/src/main/java/com/daimler/sechub/test/TestURLBuilder.java
> Feature 239 remove fp by rest api

- sechub-doc/src/docs/asciidoc/diagrams/diagram_concept_product_delgation_server_bigpicture.puml
- sechub-doc/src/docs/asciidoc/documents/architecture/08_concepts.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/product-delegation-server/product_delegation_job_config_example1.json
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/product-delegation-server/product_delegation_server.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/product-delegation-server/product_delegation_server_config_example1.json
Move documentation to implementation branch, closes #204
---
> Initial concept for #204

- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario2/FileUploadSizeScenario2IntTest.java
- sechub-server-core/src/main/java/com/daimler/sechub/server/core/SecHubExceptionHandler.java
- sechub-server-core/src/main/java/com/daimler/sechub/server/core/SecHubTomcatServletWebserverFactory.java
- renamed SecHubTomcatServletWebserverFactory.java
- fixed the max upload exception issue #292
> Rename WebserverFactory, fix for max upload exception #292 #259

- sechub-analyzer-cli/src/test/java/com/daimler/sechub/analyzer/core/FileProcessorTest.java
- sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/batch/BatchConfiguration.java
- sechub-server/src/main/resources/db/migration/V8__enlarge_project_config_data_field.sql
> Hotfix server version 0.17.2

- docs/index.md
- docs/latest/sechub-product-delegation-server.html
- sechub-doc/src/docs/asciidoc/documents/pds/about_pds.adoc
- sechub-doc/src/docs/asciidoc/sechub-product-delegation-server.adoc
> Merge server hotfix 0.17.2 into develop

- docs/latest/sechub-architecture.html
- docs/latest/sechub-client.html
- docs/latest/sechub-operations.html
- docs/latest/sechub-product-delegation-server.html
- docs/latest/sechub-quickstart-guide.html
- docs/latest/sechub-restapi.html
- docs/latest/sechub-techdoc.html
Merge back updated release documentation to develop branch
---
> Merge back updated release documentation to develop branch #380

- .github/workflows/gradle.yml
- sechub-doc/src/main/java/com/daimler/sechub/docgen/util/RestDocPathFactory.java
- sechub-doc/src/test/java/com/daimler/sechub/restdoc/ProductExecutionProfileRestControllerRestDocTest.java
- sechub-doc/src/test/java/com/daimler/sechub/restdoc/ProductExecutorConfigRestControllerRestDocTest.java
- sechub-testframework/src/main/java/com/daimler/sechub/test/TestURLBuilder.java
> Feature 408 fix build diff and openapi gen problem

- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/config/ExecutionProfileDialogUI.java
- sechub-doc/src/test/java/com/daimler/sechub/restdoc/ProductExecutionProfileRestControllerRestDocTest.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/LocalDeveloperFileSetupSupport.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario7/ProductExecutionProfileScenario7IntTest.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/product/config/ProductExecutionProfile.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/product/config/ProductExecutionProfileRestController.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/product/config/UpdateProductExecutionProfileService.java
- sechub-scan/src/test/java/com/daimler/sechub/domain/scan/product/config/UpdateProductExecutionProfileServiceTest.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/config/UseCaseAdministratorUpdatesExecutorConfig.java
> Now update does no longer update project ids, closes #409

- sechub-cli/src/daimler.com/sechub/cli/context.go
- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- read proxy settings from environment
- added documentation of proxy support
closes #322 
---
> feature 322 - add proxy support for client

- sechub-cli/src/daimler.com/sechub/cli/config.go
- sechub-cli/src/daimler.com/sechub/cli/controller.go
- sechub-cli/src/daimler.com/sechub/cli/help.go
Closes https://github.com/Daimler/sechub/issues/398
---
> #398: fixes version printing

- continous-integration-multibranch-pipeline.jenkins
> #402: removed unnecessary parameters

- sechub-sereco/src/main/java/com/daimler/sechub/sereco/importer/NetsparkerV1XMLImporter.java
- sechub-sereco/src/test/java/com/daimler/sechub/sereco/importer/NetsparkerV1XMLImporterTest.java
- sechub-sereco/src/test/java/com/daimler/sechub/sereco/test/AssertVulnerabilities.java
- sechub-sereco/src/test/java/com/daimler/sechub/sereco/test/SerecoTestFileSupport.java
- sechub-sereco/src/test/resources/netsparker/netsparker_v1.9.1.977_scan_result_output_vulnerabilities.xml
- Makes SecHub compatible with Netsparker Enterprise 1.9.1.977
- Added test for Netsparker Enterprise 1.9.1.977
> Fix Netsparker Content Identifier

- sechub.json
- change from explicitely naming directories
- to instead cover all and define excludes
closes #340
---
> Update sechub.json for sechub itself

- .github/workflows/gradle.yml
changed in github action config
Actions build was successful.
closes #442 
---
> update go-version to 1.15.3 #442

- sechub-developertools/scripts/sechub-api.sh
Create a helper Shell script for accessing the server api
- sechub-api.sh added (initial release)
- added SPDX header
closes #437 
---
>  Create a helper Shell script for accessing the server api #437

- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- added table with supported platforms
- see #397
> Add Supported Plattform Table To Client Documentation

- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario1/CheckIsAliveScenario1IntTest.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario1/ProjectAdministrationScenario1IntTest.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario3/MappingScenario3IntTest.java
- sechub-server-core/src/main/java/com/daimler/sechub/server/core/ServerErrorController.java
- sechub-test/src/test/java/com/daimler/sechub/test/RoutesTest.java
Closes https://github.com/Daimler/sechub/issues/143
---
> #143: testing all routes for sufficient assigned roles

- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/DeveloperAdministration.java
- sechub-doc/src/test/java/com/daimler/sechub/restdoc/ProjectAdministrationRestControllerRestDocTest.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java
- sechub-testframework/src/main/java/com/daimler/sechub/test/TestURLBuilder.java
> #450: fixed curl parameter order in documentations

- sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
- Added Alpine Linux 3.10, 3.11 and 3.12 for both Java 8 and Java 11
- Added Fedora 32 and 33
- Removed Fedora 31
- Smaller fixes to Quickstart Guide
---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
> Updated and improved Quickstart Guide

- sechub-scan-product-sereco/src/main/java/com/daimler/sechub/domain/scan/product/sereco/SerecoFalsePositiveMarker.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/project/FalsePositiveJobDataService.java
- sechub-scan/src/test/java/com/daimler/sechub/domain/scan/project/FalsePositiveJobDataServiceTest.java
- added audit logging actions
- renamed some methods inside fp job data service so its more
clear what happens in validation methods
- renamed junit test of fp job data service from
FalsePositiveJobServiceTest to FalsePositiveJobDataServiceTest
- added mocked audit log service to junit test dependencies
---
> Added audit logging for false positive actions, closes #501

- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
> fixed client documentation #509

- sechub-cli/src/daimler.com/sechub/cli/context-initializer.go
> don't read configfile when -help is requested

- build-spring.gradle
- sechub-doc/src/docs/asciidoc/documents/techdoc/09_04_howto_quick_test_created_sechub_server_release_local.adoc
- sechub-doc/src/docs/asciidoc/documents/techdoc/09_howtos.adoc
> Feature 487 server version

- sechub-doc/src/docs/asciidoc/documents/operations/01_sechub_server.adoc
- sechub-doc/src/docs/asciidoc/documents/operations/04_migration_steps.adoc
- sechub-doc/src/docs/asciidoc/documents/techdoc/01_development.adoc
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/TestAPI.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario4/CancelJobScenario4IntTest.java
- sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/ExecutionState.java
- sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/batch/JobRegistryBeanPostProcessorFactory.java
> Feature 499 cannot delete sechub job

- MAINTAINERS.md
> Added initial maintainers.md file #503

- build-spring.gradle
> Added junit vintage dependency, closes #563

- sechub-commons-model/src/main/java/com/daimler/sechub/commons/model/SecHubReport.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/product/config/DefaultProductExecutorConfigInfo.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/product/config/ProductExecutorConfigInfo.java
- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/product/config/WithoutProductExecutorConfigInfo.java
> #582: applying spdx headers for OSS release 0.22.0

- build.gradle
- libraries.gradle
> #591: removed jcenter dependencies

- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/AdministrationAPIConstants.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/Project.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectAdministrationRestController.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectDetailChangeService.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectDetailInformation.java
- sechub-administration/src/main/java/com/daimler/sechub/domain/administration/project/ProjectDetailInformationService.java
- sechub-administration/src/test/java/com/daimler/sechub/domain/administration/project/ProjectAdministrationRestControllerMockTest.java
- sechub-administration/src/test/java/com/daimler/sechub/domain/administration/project/ProjectDetailChangeServiceTest.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/DeveloperAdministration.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/adapter/SaveJSONAdapterDialogAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/SetProjectMockDataConfigurationAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/ShowProjectDetailAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/project/UpdateProjectDescriptionAction.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/cache/InputCacheIdentifier.java
- sechub-doc/src/test/java/com/daimler/sechub/restdoc/ProjectAdministrationRestControllerRestDocTest.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/TestAPI.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/TestRestHelper.java
- sechub-schedule/src/test/java/com/daimler/sechub/domain/schedule/SchedulerRestControllerMockTest.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/UseCaseIdentifier.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/project/UseCaseAdministratorChangesProjectDescription.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/project/UseCaseAdministratorChangesProjectDetails.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/project/UseCaseAdministratorShowsProjectDetails.java
- sechub-testframework/src/main/java/com/daimler/sechub/test/TestURLBuilder.java
> Feature 558 project comments

- continous-integration-multibranch-pipeline.jenkins
> #590: integrationtest and security scan now parallelized in the pipeline

- sechub-developertools/scripts/sechub-api.sh
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/execution_profiles.adoc
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/config/UseCaseAdministratorCreatesExecutionProfile.java
- sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/admin/config/UseCaseAdministratorFetchesExecutionProfileList.java
- scheduler handling added
- project handling extended
- profiles handling added
- executor handling added
- fixed some typos
closes #498
> enhance sechub-api shell script #498

- build-versioning.gradle
- necessary to release PDS 0.21.0
> Merge build problem fix for PDS release from devleop to master

- sechub-developertools/scripts/sechub-api.sh
additionally:
- Rest API docs linked
- eliminated double usage output in some cases
- new action help
closes #634
> new action project_create implemented for sechub-api script

- sechub-cli/src/daimler.com/sechub/cli/config.go
- sechub-cli/src/daimler.com/sechub/cli/config_test.go
> remove trailing slashes from server url if present

- .github/workflows/create-releases.yml
- build-versioning.gradle
- buildExecutables
- buildSrc/src/main/groovy/VersionData.groovy
- sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
> Feature 690 fix dirty flag on release builds

- sechub-pds/build.gradle
Added PostgreSQL to PDS dependencies.
closes: #702
> Added PostgreSQL driver to PDS dependencies

- sechub-pds/build.gradle
Fix missing PostgreSQL driver
see: #702
> fix missing postgresql driver

- sechub-pds/build.gradle
> Fix missing PostgreSQL

- sechub-pds/src/main/resources/application-pds_integrationtest.yml
- sechub-server/src/main/resources/application-integrationtest.yml
> Integration test profiles now only available on loopback address #719

- sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
Added Go to the quick start guide
closes: #713
> Added Go to the quick start guide

- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/ExecutionConstants.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/IntegrationTestDefaultExecutorConfigurations.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/IntegrationTestDefaultProfiles.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/ScenarioInitializer.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/scenario5/Scenario5.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/scenario6/Scenario6.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/scenario9/Scenario9.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario5/PDSCodeScanJobScenario5IntTest.java
- sechub-pds/src/main/java/com/daimler/sechub/pds/batch/PDSBatchTriggerService.java
- sechub-pds/src/main/java/com/daimler/sechub/pds/execution/PDSExecutionCallable.java
- sechub-pds/src/main/java/com/daimler/sechub/pds/job/PDSJobRepositoryCustom.java
- sechub-pds/src/main/java/com/daimler/sechub/pds/job/PDSJobRepositoryImpl.java
- sechub-pds/src/main/java/com/daimler/sechub/pds/job/PDSJobTransactionService.java
- sechub-pds/src/test/java/com/daimler/sechub/pds/batch/PDSBatchTriggerServiceTest.java
> Avoid duplicated execution of PDS jobs #714

- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario3/FalsePositivesScenario3IntTest.java
- sechub-pds/src/main/java/com/daimler/sechub/pds/PDSServerErrorController.java
- sechub-pds/src/test/java/com/daimler/sechub/pds/PDSServerErrorControllerTest.java
- sechub-server-core/src/main/java/com/daimler/sechub/server/core/ServerErrorController.java
- sechub-server-core/src/test/java/com/daimler/sechub/server/core/ServerErrorControllerTest.java
> Implemented error message handling on JSON results #734

- sechub-integrationtest/ciphertest.sh
> Use generic path to bash #756

- sechub-cli/src/daimler.com/sechub/cli/constants.go
- sechub-cli/src/daimler.com/sechub/testutil/asserts.go
- sechub-cli/src/daimler.com/sechub/testutil/fileTestHelpers.go
- sechub-cli/src/daimler.com/sechub/util/filepathmatcher.go
- sechub-cli/src/daimler.com/sechub/util/filepathmatcher_test.go
- sechub-cli/src/daimler.com/sechub/util/zip.go
- sechub-cli/src/daimler.com/sechub/util/zip_test.go
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario2/SecHubExecutionScenarioSecHubClientIntTest.java
Fix for #754
- SecHub Client fixed (also simplified zip procedure)
- Client unit tests added
- some adaptions to integration tests due to changed client
Closes #754
> Feature 754 client consistent zip

- .github/workflows/create-releases.yml
- .github/workflows/gradle.yml
Hi ! This is using the built-in cache of setup-java and also reindent workflows files
> chore(ci): use built-in cache of setup-java and indent workflows files

- libraries.gradle
Upgrade JSoup #776 .
Closes: #776
> upgrade jsoup

- sechub-pds-examples/gosec/10-create-ubuntu-image.sh
- sechub-pds-examples/gosec/11-create-alpine-image.sh
Add pull command to docker build instructions.
Closes: #791
> Add pull command to docker build instructions.

- sechub-adapter-pds/src/main/java/com/daimler/sechub/adapter/pds/PDSAdapterV1.java
- sechub-adapter/src/main/java/com/daimler/sechub/adapter/AbstractAdapterConfig.java
- sechub-adapter/src/main/java/com/daimler/sechub/adapter/AbstractAdapterConfigBuilder.java
- sechub-adapter/src/main/java/com/daimler/sechub/adapter/TimeConstants.java
- sechub-adapter/src/test/java/com/daimler/sechub/adapter/AbstractAdapterConfigBuilderTest.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/DeveloperAdministration.java
- sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/ShowProductExecutorTemplatesDialogActionFactory.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/IntegrationTestDefaultExecutorConfigurations.java
- sechub-scan-product-checkmarx/src/main/java/com/daimler/sechub/domain/scan/product/checkmarx/CheckmarxProductExecutor.java
- sechub-scan-product-nessus/src/main/java/com/daimler/sechub/domain/scan/product/nessus/NessusProductExecutor.java
- sechub-scan-product-netsparker/src/main/java/com/daimler/sechub/domain/scan/product/netsparker/NetsparkerInstallSetupImpl.java
- sechub-scan-product-netsparker/src/main/java/com/daimler/sechub/domain/scan/product/netsparker/NetsparkerProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSCodeScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSExecutorConfigSuppport.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSInfraScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSInstallSetup.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSInstallSetupImpl.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSProductExecutorKeyProvider.java
- sechub-scan-product-pds/src/main/java/com/daimler/sechub/domain/scan/product/pds/PDSWebScanProductExecutor.java
This PR will
- close #785 
- close #787
> Bugfix + improved PDS period time check by providing milliseconds instead of minutes in configurations

- sechub-scan/src/main/java/com/daimler/sechub/domain/scan/report/ScanReport.java
- sechub-server/src/main/resources/db/migration/U14__sechub_report_type_bugfix2.sql
- sechub-server/src/main/resources/db/migration/V14__sechub_report_type_bugfix.sql
> Feature 877 bugfix old reports not fetchable

- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/IntegrationTestSetup.java
- closes #884 
- now the IntegrationTestSetup junit rule does ensure that after
server start, the user used internally as super admin by TestAPI
can access the user signups. This ensures the admin is created and
has full access. If error happens this will be retried until time out
or user has rights.
> Ensure internal test user has full access before tests execution #884

- sechub-doc/build.gradle
> Updated asciidoctorj dependencies to fix render problems #867

- build-maven.gradle
- sechub-developertools/build.gradle
- sechub-integrationtest/build.gradle
- sechub-shared-kernel/build.gradle
> Fix problem with versions on library modules #890

- sechub-pds-solutions/gosec/70-test.sh
Increase the default retry limit to 1200.
> Feature 906 increase interation limit in SAST test script

- sechub-developertools/scripts/sechub-api.sh
> Fix secub-api.sh helper script: refresh before status

- sechub-developertools/scripts/sechub-api.sh
> sechub-api.sh helper script: project_set_accesslevel implemented

- sechub-pds-solutions/gosec/01-start-single-docker-compose.sh
- sechub-pds-solutions/gosec/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/gosec/docker/database/Dockerfile
- sechub-pds-solutions/gosec/docker/database/postgresql.conf
- sechub-pds-solutions/gosec/docker/database/run.sh
- sechub-pds-solutions/gosec/docker/loadbalancer/Dockerfile
- sechub-pds-solutions/gosec/docker/loadbalancer/nginx.conf
- sechub-pds-solutions/gosec/docker/object-storage/Dockerfile
- sechub-pds-solutions/gosec/docker/object-storage/run.sh
- Switch LoadBalancer to Ubuntu
- Switch ObjectStorage to Ubuntu
- Switch Postgre to Ubuntu
close: #927
> Switch the supporting Dockerfiles to Ubuntu

- build.gradle
- libraries.gradle
Upgrade dependencies:
- Upgrade SpringBoot from 2.5.7 to 2.5.8 #909
- Upgrade database dependencies #913
- Upgrade Apache Commons and Apache HTTP dependencies #913
- Upgrade logstash #913
closes: #909
closes: #913
> Upgrade dependencies

- sechub-pds-solutions/gosec/helm/pds-gosec/Chart.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- startupProbe+livenessProbe added
- set container port as variable (avoid redundancy)
closes #943
> Feature943 pds go sec startup probe

- sechub-commons-pds/src/main/java/com/daimler/sechub/commons/pds/PDSConfigDataKeyProvider.java
@Jeeppler typos fixed as you asked to do, if there is any other please let me know.
> typos fixed

- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
Changes are basically that the SecHub job gets created after the generation of the local .zip file succeeded.
closes #106
> Feature 106 create job after zipping

- sechub-cli/src/mercedes-benz.com/sechub/cli/false-positives.go
> Feature 557/971 interactive mark/unmark false positives empty list handling

- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/report.go
- check status before download
- exit on non-OK with error message
- simplified code by including jobStatusResult into Context struct
closes #977
> Feature 977 client status check before download

- .gitignore
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
Very small change/optimization:
In `controller.go`, variable `fileEnding` was eliminated.
Additionally an example comment was added.
closes #980
> code optimized #980

- sechub-adapter-checkmarx/src/test/java/com/daimler/sechub/adapter/checkmarx/CheckmarxAdapterTestApplication.java
- sechub-doc/src/test/java/com/daimler/sechub/docgen/util/TextFileWriterTest.java
- sechub-integrationtest/build.gradle
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/WithSecHubClient.java
- sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/SecHubClientExecutor.java
- sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/internal/PersistentScenarioTestDataProviderTest.java
- sechub-pds/src/test/java/com/daimler/sechub/pds/config/PDSPathExecutableValidatorTest.java
- sechub-pds/src/test/java/com/daimler/sechub/pds/job/PDSFileUploadJobServiceTest.java
- sechub-pds/src/test/java/com/daimler/sechub/pds/job/PDSWorkspaceServiceTest.java
- sechub-pds/src/test/java/com/daimler/sechub/pds/util/PDSFileUnzipSupportTest.java
- sechub-scan/src/test/java/com/daimler/sechub/domain/scan/admin/FullScanDataToZipOutputSupportTest.java
- sechub-storage-s3-aws-test/src/test/java/com/daimler/sechub/storage/s3/AwsS3JobStorageTest.java
- sechub-storage-sharedvolume-spring/build.gradle
- sechub-storage-sharedvolume-spring/src/main/java/com/daimler/sechub/storage/sharevolume/spring/AbstractSharedVolumePropertiesSetup.java
- sechub-storage-sharedvolume-spring/src/test/java/com/daimler/sechub/storage/sharevolume/spring/SharedVolumeJobStorageTest.java
- sechub-test/src/test/java/com/daimler/sechub/test/report/ThymeLeafHTMLReportingTest.java
- sechub-testframework/src/main/java/com/daimler/sechub/test/TestFileSupport.java
- sechub-testframework/src/main/java/com/daimler/sechub/test/TestUtil.java
- sechub-testframework/src/test/java/com/daimler/sechub/test/TestUtilTest.java
> Feature 651 tmp files inside build folders

- apply-headers.sh
> exclude patterns added #1004

- .github/workflows/gradle.yml
- ./gradlew documentation is sufficient
- source HTML directory location fixed
closes #1035
> fix html artifact generation #1035

- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/importer/SarifV1JSONImporter.java
- sechub-sereco/src/test/java/com/mercedesbenz/sechub/sereco/importer/SarifV1JSONImporterTest.java
- sechub-sereco/src/test/java/com/mercedesbenz/sechub/sereco/test/AssertVulnerabilities.java
- sechub-sereco/src/test/java/com/mercedesbenz/sechub/sereco/test/VulnerabilityTestDescriptionBuilder.java
- sechub-sereco/src/test/resources/sarif/sarif_2.1.0_gosec_2.9.5_example5_codescan.sarif.json
> Handle Sarif location snippet #956

- .github/workflows/create-releases.yml
> Feature 1060 autocreate release issues

- sechub-api-java/generateAPI.sh
Remark: The build workflow will fail, because the until now undiscovered build problems are visible now. They should be addressed in a separate PR.
closes #1069
> fail if a script step fails #1069

- build.gradle
- libraries.gradle
- sechub-api-java/build-publish-github-packages.gradle
- sechub-doc/build.gradle
- Upgrade OpenAPI dependencies #912
- Fix OpenAPI generation issue #1075
Closes: #912
Closes: #1075
> Upgrade dependencies and fix OpenAPI generation issue

- sechub-pds-solutions/gosec/docker/GoSec-Ubuntu.dockerfile
- sechub-pds-solutions/gosec/docker/mock.sarif.json
- Upgrade GoSec
- Upgrade Go
- Update SARIF mock 
closes: #968
closes: #967
> upgrade GoSec, Go and sarif mock #968

- sechub-api-java/generateAPI.sh
> Disabled Github packages #1084

- sechub-pds-solutions/gosec/docker/GoSec-Ubuntu.dockerfile
- sechub-pds-solutions/multi/docker/Multi-Ubuntu.dockerfile
- sechub-pds-solutions/multi/docker/mocks/bandit_mock.sarif.json
- sechub-pds-solutions/multi/docker/packages.txt
- Upgrade PDS in GoSec
- Upgrade PDS in Multi
- Upgrade Bandit in PDS + Multi
closes: #1096
> Upgrade PDS in PDS Solutions #1096

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/PDSFlywayFactory.java
- sechub-server/src/main/java/com/mercedesbenz/sechub/server/SecHubServerFlywayFactory.java
This PR
- closes #1104
- closes #1106
> Hotfix flyway checksum failing

- MAINTAINERS.md
> Update active maintainer email addresses because of rebrand #1116

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertAutoCleanupInspections.java
> Replaced wrong import and use now Objects.equals() instead #1135

- sechub-cli/build.gradle
- sechub-cli/build_go.sh
- sechub-cli/script/supported-source-extensions.txt
- new file extensions added
- removed verbosity flag for Go tests
- silenced pushd in Shellscript
closes #1130
> new file extensions added #1130

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- more flexibility in passing args (action can be passed other than last arg)
- default to help screen on empty action
- unit test added
closes #894
> Feature 894 client parameter flexibility

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- passing via cmdline argument added
- passing via env var added
- unit tests
- verification if the dir exists and is a dir
- documentation update
- documentation wording improvements
- zipfile renamed because at creation time, no jobUUID exists yet
closes #467
> Make temporary directory configurable #467

- sechub-doc/build.gradle
> Fix gradle build problems #1144

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/BinderControllerAdvice.java
- sechub-server/src/main/java/com/mercedesbenz/sechub/server/BinderControllerAdvice.java
This PR 
- closes #1178
- closes #1179
> Security improvements #1178, #1179

- sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go
- sechub-cli/src/mercedes-benz.com/sechub/util/errorhandler.go
- also improved HTTP error output
closes #1162
> resilience handling improved #1162

- .github/workflows/create-releases.yml
Add checksums in format that can easily checked by sha256sum command.
SecHub server:
- sechub-developertools-....jar
- sechub-server-....jar
PDS release:
- sechub-pds-....jar
Also removed unused step IDs.
closes #1020 
closes #923
closes #374
> Feature 1020 build sha256sums

- sechub-pds-solutions/gosec/docker/GoSec-Ubuntu.dockerfile
- sechub-pds-solutions/gosec/docker/mock.sarif.json
- Upgrade Go to 1.18
- Upgrade PDS to 0.26.2
- Upgrade GoSec to 2.11.0
closes: #1208
> Feature 1208 go gosec upgrade

- sechub-developertools/scripts/sechub-api.sh
New actions:
- autocleanup_get
- autocleanup_set
closes #1207
> Feature 1207 sechub api.sh auto cleanup configuration

- sechub-doc/src/docs/asciidoc/documents/pds/pds_config.adoc
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentService.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentServiceTest.java
> Introduce SECHUB_JOB_UUID environment variable in PDS scripts #1219

- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/config/AdministrationConfig.java
- sechub-server/src/main/resources/db/migration/U15__provide_auto_cleanup.sql
- sechub-server/src/main/resources/db/migration/U16__rename_admin_config_to_adm_config.sql
- sechub-server/src/main/resources/db/migration/V16__rename_admin_config_to_adm_config.sql
This PR
- closes #1205 
- closes #1204
> fix-1204-rename-admin_config-table-to-adm_config 

- continous-integration-multibranch-pipeline.jenkins
- gradle calls improved
- server+client builds now parallel
- indentation fixes
closes #1241
> Jenkins ci-pipeline updated #1241

- .github/workflows/create-releases.yml
- .github/workflows/gradle.yml
- sechub-pds-solutions/gosec/docker/GoSec-Ubuntu.dockerfile
> Feature 1256 upgrade go to 1.18

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller_test.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip_test.go
- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- `SECHUB_WHITELIST_ALL` env var handling added
- unit tests added
- `ReadContentOfZipFile()` made public for access from SecHub cli package
closes #905
> Merge feature 905 client no filter option

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/util/fileHelpers.go
- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
- order fixed in assertValidConfig()
- search directory if now fixed "." as documented
- debug flag added for FindNewestMatchingFileInDir()
- docs updated
- unit test added
closes #1239
> fixed interactiveMarkFalsePositives #1239

- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
> Added missing documentation parts about client only options #1148

- sechub-adapter/src/main/java/com/mercedesbenz/sechub/adapter/AbstractWebScanAdapterConfigBuilder.java
- sechub-adapter/src/test/java/com/mercedesbenz/sechub/adapter/AbstractWebScanAdapterConfigBuilderTest.java
- sechub-scan-product-netsparker/src/main/java/com/mercedesbenz/sechub/domain/scan/product/netsparker/NetsparkerProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSWebScanProductExecutor.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/NetworkTargetRegistry.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/TargetResolverService.java
This PR
- closes #1265 
- closes #1267
> Feature 1265 pds scan target type env not set

- sechub-cli/script/supported-source-extensions.txt
> IaC source files added to whitelist #1247

- sechub-cli/build_go.sh
> client support platform  ARM on MacOS #515

- sechub-developertools/scripts/sechub-api.sh
- added job create, upload and approve commands
- added get spdx report commands #1285
closes: #1285
> Job crate, upload and approve as well as get SPDX report commands

- sechub-pds-solutions/gosec/helm/pds-gosec/Chart.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/values.yaml
- sechub-pds-solutions/multi/helm/pds-multi/Chart.yaml
- sechub-pds-solutions/multi/helm/pds-multi/templates/deployment.yaml
- sechub-pds-solutions/multi/helm/pds-multi/values.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/values.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/Chart.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/templates/deployment.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/values.yaml
enable logging type for pds-solutions:
- pds-gosec
- pds-multi
- pds-owaspzap
- pds- scancode
closes #1306
> Feature 1306 pds solutions enable logging type

- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/product/ProductResultService.java
> Activate service security check for 'delete all results for job'.

- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/ShowProductExecutorTemplatesDialogActionFactory.java
- added license scan dialog #1315
closes: #1315
> added license scan dialog #1315

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
> Updated link to FOSS repository of mercedes-benz #1344

- sechub-cli/script/go-gen-supported-source-extensions.sh
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/util/archiveHelpers.go
- sechub-cli/src/mercedes-benz.com/sechub/util/fileHelpers.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip_test.go
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds_handle_storage_parts_at_runtime.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_data_section_general_example2.json
- SecHub client supports data section in JSON config for source code
- still compatible with old/legacy format
- unit tests added
- several naming and typo fixes
closes #1161
> Feature 1161 client handles data section

- sechub-cli/src/mercedes-benz.com/sechub/cli/context.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/tarbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/tarbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/testutil/asserts.go
- sechub-cli/src/mercedes-benz.com/sechub/util/archiveHelpers.go
- sechub-cli/src/mercedes-benz.com/sechub/util/filepathmatcher.go
- sechub-cli/src/mercedes-benz.com/sechub/util/filepathmatcher_test.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar_test.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip.go
also:
- added unit tests
- removed term 'zip' out of some generic functions
- fixed output for http debugging
- fixed test function
closes #1155
> upload of binaries tar implemented #1155

- sechub-pds-solutions/pmd/docker/PMD-Ubuntu.dockerfile
- sechub-pds-solutions/pmd/docker/mocks/mock-option-all.sarif.json
- sechub-pds-solutions/pmd/docker/mocks/mock-option-security.sarif.json
- sechub-pds-solutions/pmd/docker/pds-config.json
- sechub-pds-solutions/pmd/docker/pmd_mock.sh
> Create PMD + PDS mock environment.

- sechub-doc/src/docs/asciidoc/documents/operations/server/server_deployment.adoc
- sechub-doc/src/docs/asciidoc/documents/pds/pds_config.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/pds_options.adoc
- sechub-integrationtest/pds/product-scripts/integrationtest-codescan.sh
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertUser.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/IntegrationTestSetup.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/NoSecHubSuperAdminNecessaryScenario.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/scenario6/Scenario6.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario6/DirectPDSAPIJobScenario6IntTest.java
- sechub-pds-core/src/main/java/com/mercedesbenz/sechub/pds/PDSLogConstants.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionCallable.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSLauncherScriptEnvironmentConstants.java
This PR
- closes #863 
- closes #1354
- closes #1380
> Introduced env variable `PDS_JOB_UUID` #863

- sechub-integrationtest/integrationtest-pds.sh
- sechub-integrationtest/integrationtest-server.sh
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/IntegrationTestPDSRestController.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionService.java
> Fixes PDS shutdown problem #998

- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_status_dataflow.adoc
> Client handles server messages

- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/IntegrationTestDataMenuAppender.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/action/ActionSupport.java
> Fixes DAUI problem with missing mock data file when not in IDE #1389

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/report.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder_test.go
spdx report format implemented
closes #1397
> Feature 1397 client supports spdx-json reports

- sechub-integrationtest/integrationtest-pds.sh
- sechub-integrationtest/integrationtest-server.sh
> Feature 1388 improvements integrationserver scripts

- sechub-integrationtest/integrationtest-pds.sh
- sechub-integrationtest/integrationtest-server.sh
> Feature 1404 fix start stop scripts

- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
Please see my comment in #810
closes #810
> trafficlight `OFF` implemented #810

- sechub-developertools/build.gradle
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/DeveloperArchiveSupport.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/OutputHandler.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/SystemOutputHandler.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/ComboxSelectionDialogUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/ConfigurationSetup.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/DialogUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/OutputUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/action/pds/GeneratePDSSolutionTestFilesAction.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/pds/PDSSolutionTestFilesGenerator.java
> Implemented PDS test file generation as action + CLI tool #1420

- sechub-pds-solutions/scancode/docker/ScanCode-Debian.dockerfile
- sechub-pds-solutions/scancode/helm/pds-scancode/templates/deployment.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/values.yaml
- fix mount path in Helm 
- add procs package
> fix mount path in Helm and add procs package #1439

- sechub-pds-solutions/scancode/docker/run.sh
remove logging of S3 key from bash script
closes: #1441
> Remove logging of S3 key from bash script

- sechub-pds-solutions/pmd/10-create-image.sh
- sechub-pds-solutions/pmd/20-push-image.sh
- sechub-pds-solutions/pmd/helm/pds-pmd/.helmignore
- sechub-pds-solutions/pmd/helm/pds-pmd/Chart.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/LICENSE
- sechub-pds-solutions/pmd/helm/pds-pmd/README.md
- sechub-pds-solutions/pmd/helm/pds-pmd/templates/deployment.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/templates/networkpolicy.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/templates/service.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/values.yaml
Create a Helm Chart for the PMD+PDS.
This PR closes #1376
> Create a Helm Chart for the PMD+PDS

- build.gradle
- gradle/libraries.gradle
- gradle/spring_boot_dependagen.gradle
We forgot to run dependagen.
- Upgrade the Spring Boot 2.7.1 dependencies
- Upgrade other dependencies
closes: #1447
> Upgrade dependencies to spring boot 2.7.1

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsPDSUser.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/TestAPI.java
> Enhance auto dump mechanism and fix stackoverflow problem #1464

- sechub-integrationtest/pds/product-scripts/integrationtest-codescan.sh
- sechub-integrationtest/pds/product-scripts/test_shared-functions.sh
> Replaced tree command call with ls variant , fixes #1469

- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/values.yaml
I mistakenly changed the version of the Chart.yaml to `0.7.0` on the previous Pull Request, but did not change the Helm Chart at all. Because of this I did not update the Helm Chart version by now in this Pull Request. **Should this be done anyway?**
- closes #1472
> Implement a solution to limit the memory resources of pds-owaspzap #1472

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubMessagesList.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionCallable.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionCallableFactory.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSProcessAdapterFactory.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/ProcessAdapter.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionCallableTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionServiceTest.java
- sechub-pds/src/test/resources/testdata/workspace1/job1/error.txt
- sechub-pds/src/test/resources/testdata/workspace1/job1/messages/message1.txt
- sechub-pds/src/test/resources/testdata/workspace1/job1/metadata.txt
- sechub-pds/src/test/resources/testdata/workspace1/job1/output.txt
- sechub-pds/src/test/resources/testdata/workspace1/job1/result.txt
> PDS Product time out writes now execution data into DB, fixes #1523

- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveJobDataListValidationImpl.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveJobDataService.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveJobDataListValidationImplTest.java
This PR
- closes #1541
- closes #1542
> Enhanced server validation for false positives #1541

- continous-integration-multibranch-pipeline.jenkins
- sechub-doc/src/docs/asciidoc/documents/buildserver/jenkins-pipeline.adoc
> Jenkins pipeline with variable #1343

- sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
> html download documented #1369

- sechub-doc/src/docs/asciidoc/documents/operations/02_security_products.adoc
- sechub-pds-solutions/README.adoc
> typo fixed #818

- continous-integration-multibranch-pipeline.jenkins
- release-pipeline.jenkins
- trigger job `sechub-pds-released` in release pipeline
- only build everything when release tags are set
- code cleanup (removed unused mehtods etc.)
- integrationtest stage fixed
closes #1368 
closes #1564
> Feature 1368 jenkins trigger pds release job

- sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar_test.go
- also HTTP debugging consolidated
closes #1552 
closes #1572
> x-file-size header set #1552

- sechub-developertools/scripts/sechub-api.sh
- added handling for a user's email change
- added handling for a project's whitelist urls
- fixed wrong help text for "user_reset_apitoken"
closes #1577
> Feature 1577 improve sechub api.sh script

- sechub-developertools/scripts/sechub-api.sh
> debug output removed #1583

- sechub-api-java/build.gradle
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/SecHubClient.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/CommandLineParser.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/CommandLineSettings.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/EnvironmentVariableConstants.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/EnvironmentVariableReader.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/OpenAPITestTool.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/README.adoc
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/SecHubClientConfigurationFactory.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/SechubServerTest.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/exceptions/OpenAPITestToolRuntimeException.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/cli/exceptions/SecHubClientConfigurationRuntimeException.java
Create small CLI tool for testing the OpenAPI java client #1506.
Closes #1506.
> Create small CLI tool for testing the OpenAPI java client #1506.

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubFinding.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/Severity.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubFindingTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario10/PDSCodeScanSarifJobScenario10IntTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario9/PDSCodeScanSarifJobScenario9IntTest.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoProductResultTransformer.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoProductResultTransformerTest.java
> Feature 1284 sort findings by severity CWE CVE

- .github/workflows/create-pds-tools-release.yml
- gradle/build-versioning.gradle
- sechub-pds-tools/build.gradle
> Feature 1637 fix pds tools release build

- .gitattributes
> Added git attribute file with auto crlf for all #1654

- sechub-pds-solutions/findsecuritybugs/01-start-single-docker-compose.sh
- sechub-pds-solutions/findsecuritybugs/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/findsecuritybugs/50-start-multiple-docker-compose.sh
- sechub-pds-solutions/findsecuritybugs/51-start-multiple-object-storage-docker-compose.sh
- sechub-pds-solutions/gitleaks/01-start-single-docker-compose.sh
- sechub-pds-solutions/gosec/01-start-single-docker-compose.sh
- sechub-pds-solutions/gosec/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/gosec/50-start-multiple-docker-compose.sh
- sechub-pds-solutions/gosec/51-start-multiple-object-storage-docker-compose.sh
- sechub-pds-solutions/multi/01-start-single-docker-compose.sh
- sechub-pds-solutions/multi/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/multi/50-start-multiple-docker-compose.sh
- sechub-pds-solutions/multi/51-start-multiple-object-storage-docker-compose.sh
- sechub-pds-solutions/owasp-zap/01-start-single-docker-compose.sh
- sechub-pds-solutions/owasp-zap/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/owasp-zap/50-start-multiple-docker-compose.sh
- sechub-pds-solutions/owasp-zap/51-start-multiple-object-storage-docker-compose.sh
- sechub-pds-solutions/pds-base/01-start-single-docker-compose.sh
- sechub-pds-solutions/pmd/01-start-single-docker-compose.sh
- sechub-pds-solutions/pmd/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/pmd/50-start-multiple-docker-compose.sh
- sechub-pds-solutions/pmd/51-start-multiple-object-storage-docker-compose.sh
- sechub-pds-solutions/scancode/01-start-single-docker-compose.sh
- sechub-pds-solutions/scancode/05-start-single-sechub-network-docker-compose.sh
- sechub-pds-solutions/scancode/50-start-multiple-docker-compose.sh
- sechub-pds-solutions/scancode/51-start-multiple-object-storage-docker-compose.sh
* Updated all scripts to docker compose v2 ('docker compose' instead 'docker-compose') in the 'sechub-pds-solutions' folder
Closes #1670
> Upgraded to Docker Compose CLI v2

- sechub-pds-solutions/gosec/helm/pds-gosec/Chart.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/values.yaml
- sechub-pds-solutions/pds-base/docker/run.sh
> PDS-GoSec container startup failure fixed

- sechub-pds-solutions/gosec/helm/pds-gosec/Chart.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/values.yaml
- sechub-pds-solutions/pds-base/docker/run.sh
> Added pds heartbeat logging config #1694

- build.gradle
- gradle/libraries.gradle
- gradle/spring_boot_dependagen.gradle
- Upgrade Spring Boot to 2.7.5
- Upgrade non Spring Boot dependencies
closes: #1659
> Feature 1659 upgrade to spring boot 2.7.5

- sechub-server/src/main/resources/application.yml
> Fixed missing spring batch tables in initial server startup #1691

- sechub-pds-solutions/README.adoc
- sechub-solution/README.adoc
- sechub-solutions-shared/README.adoc
Added readme files for sechub-solution and sechub-solutions-shared #1705
closes: #1705
> Added readme files for sechub-solution and sechub-solutions-shared #1705

- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/Chart.yaml
- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/templates/deployment.yaml
- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/values.yaml
Added heartbeat logging to PDS Checkmarx Solution
> Added PDS heartbeat logging to pds cx

- sechub-integrationtest/integrationtest-server.sh
> export variable to fix #1714

- sechub-developertools/scripts/sechub-api.sh
> #1605 implemented

- sechub-developertools/scripts/sechub-api.sh
> filter http headers #1725

- sechub-pds-solutions/pds-base/docker/PDS-Debian.dockerfile
- sechub-pds-solutions/pds-base/docker/helper/message.sh
- sechub-pds-solutions/pds-base/docker/scripts/pds.sh
- sechub-pds-solutions/pds-base/env
Added message.sh script to helper folder
closes: #1632
> Added message.sh script to helper folder

- sechub-pds-solutions/gosec/10-create-image.sh
- sechub-pds-solutions/scancode/10-create-image.sh
- sechub-pds-solutions/scancode/docker/ScanCode-Debian.dockerfile
- sechub-pds-solutions/scancode/docker/packages.txt
> Feature 1733 pds scancode improvements

- sechub-doc/src/docs/asciidoc/sechub-architecture.adoc
- sechub-doc/src/docs/asciidoc/sechub-client.adoc
- sechub-doc/src/docs/asciidoc/sechub-operations.adoc
- sechub-doc/src/docs/asciidoc/sechub-product-delegation-server.adoc
- sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
- sechub-doc/src/docs/asciidoc/sechub-restapi.adoc
- sechub-doc/src/docs/asciidoc/sechub-techdoc.adoc
> clicking SecHub logo leads to main docs page #368

- sechub-notification/src/main/java/com/mercedesbenz/sechub/domain/notification/NotificationMessageHandler.java
- sechub-notification/src/main/java/com/mercedesbenz/sechub/domain/notification/user/SignUpRequestedUserNotificationService.java
- sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/NotificationMessageHandlerTest.java
- sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/user/SignUpRequestedUserNotificationServiceTest.java
Send an email to user about his/her self-registration. #156
> Send an email to user about his/her self-registration. #156

- sechub-commons-pds/src/main/java/com/mercedesbenz/sechub/commons/pds/PDSConfigDataKeyProvider.java
- sechub-commons-pds/src/main/java/com/mercedesbenz/sechub/commons/pds/PDSDefaultParameterKeyConstants.java
- sechub-integrationtest/pds/product-scripts/integrationtest-checkmarx.sh
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/IntegrationTestDefaultExecutorConfigurations.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario17/PDSCheckmarxIntegrationScenario17IntTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario9/PDSCodeScanSarifJobScenario9IntTest.java
> Added `pds.debug.enabled` as default job parameter #1741

- sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/PDSExecutorConfigurationParameterDescriptionGenerator.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSAdapterConfigurationStrategy.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSCodeScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSExecutorConfigSupport.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSInfraScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSLicenseScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSWebScanProductExecutor.java
- sechub-scan-product-pds/src/test/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSAdapterConfigurationStrategyBulderTest.java
- sechub-scan-product-pds/src/test/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSExecutorConfigSupportTest.java
> Feature 1712 environments in executor config

- sechub-pds-solutions/checkmarx/20-push-image.sh
- sechub-pds-solutions/findsecuritybugs/20-push-image.sh
- sechub-pds-solutions/gosec/20-push-image.sh
- sechub-pds-solutions/multi/20-push-image.sh
- sechub-pds-solutions/owasp-zap/20-push-image.sh
- sechub-pds-solutions/pds-base/20-push-image.sh
- sechub-pds-solutions/pmd/20-push-image.sh
- sechub-pds-solutions/scancode/20-push-image.sh
- sechub-pds-solutions/shared/README.adoc
- sechub-pds-solutions/shared/scripts/20-push-image.sh
- sechub-pds-solutions/tern/20-push-image.sh
also added a readme file for the `shared/` folder
closes #1738
> eliminate redundant scripts #1738

- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/values.yaml
also
- completed missing attributes in values.yaml
- whitespace in gosec's deployment.yaml
closes #1766
> fix heartbeat logging #1766

- sechub-pds-solutions/checkmarx/10-create-image.sh
> Fixed BUILD_TYPE fallback #1771

- build.gradle
- gradle/libraries.gradle
- gradle/spring_boot_dependagen.gradle
- Upgrade Spring Boot to 2.7.6
- Upgrade dependencies
closes: #1703
> Upgrade to Spring Boot to 2.7.6

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/TestAPI.java
- sechub-server-core/src/main/java/com/mercedesbenz/sechub/server/core/IntegrationTestServerRestController.java
> Fixes integration test problems with S3 #1780

- sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/AsciidocGenerator.java
> Removed unnecessary asciidoc generation #1788

- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example2_webscan_anonyous.json
- sechub-doc/src/test/java/com/mercedesbenz/sechub/ExampleFile.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/ExampleFilesValidTest.java
> Update webscan config documentation

- build.gradle
- gradle/libraries.gradle
- gradle/wrapper/gradle-wrapper.properties
- sechub-analyzer-cli/src/main/java/com/mercedesbenz/sechub/analyzer/cli/SecHubAnalyzerApplication.java
- sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/AsciidocGenerator.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertUser.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/IntegrationTestSetup.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/TestAPI.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/monitoring/PerformanceMonitorServiceManualTest.java
Upgrade Gradle and some dependencies:
- Gradle to 7.6 #1799
- AWS SDK
- S3 Mock
- Spotless -> required another Spotless Apply
closes: #1799
> Feature 1799 upgrade to gradle 7.6

- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/configuration/AbstractAllowSecHubAPISecurityConfiguration.java
> Extend CSP header settings to allow CSS

- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/Chart.yaml
- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/templates/deployment.yaml
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/Chart.yaml
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/templates/deployment.yaml
- sechub-pds-solutions/gosec/docker/pds-config.json
- sechub-pds-solutions/gosec/helm/pds-gosec/Chart.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/multi/helm/pds-multi/Chart.yaml
- sechub-pds-solutions/multi/helm/pds-multi/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/Chart.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/templates/deployment.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/Chart.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/templates/deployment.yaml
Helm charts/templates changed:
- default to 1 db connection
- max 2 connections (except pds-owaspzap which runs only one at a time)
closes #1822
> limit database connection pool #1822

- sechub-commons-core/src/main/java/com/mercedesbenz/sechub/commons/core/FailableRunnable.java
- sechub-commons-core/src/main/java/com/mercedesbenz/sechub/commons/core/util/SimpleStringUtils.java
- sechub-commons-core/src/test/java/com/mercedesbenz/sechub/commons/core/util/SimpleStringUtilsTest.java
- sechub-commons-pds/src/main/java/com/mercedesbenz/sechub/commons/pds/PDSConfigDataKeyProvider.java
- sechub-commons-pds/src/main/java/com/mercedesbenz/sechub/commons/pds/PDSDefaultParameterKeyConstants.java
- sechub-commons-pds/src/main/java/com/mercedesbenz/sechub/commons/pds/PDSDefaultParameterValueConstants.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CredentialUI.java
- sechub-pds-core/src/main/java/com/mercedesbenz/sechub/pds/job/PDSJobConfigurationSupport.java
- sechub-pds-core/src/test/java/com/mercedesbenz/sechub/pds/job/PDSJobConfigurationSupportTest.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/config/PDSConfigurationAutoFix.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSWorkspacePreparationContext.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSWorkspacePreparationContextFactory.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSWorkspaceService.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/util/PDSResilientRetryExecutor.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/config/PDSConfigurationAutoFixTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/job/PDSWorkspacePreparationContextFactoryTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/util/PDSResilientRetryExecutorTest.java
> Implemented simple resilience PDS storage read #1805

- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/values.yaml
> workerThreadCount is pinned to 1 #1825

- sechub-pds-solutions/pds-base/docker/run.sh
- sechub-pds-solutions/pds-base/docker/run_additional.sh
> run_additional.sh script restored #1839

- sechub-pds-solutions/owasp-zap/10-create-image.sh
> usage help improved #1845

- build.gradle
- gradle/libraries.gradle
- gradle/spring_boot_dependagen.gradle
- Upgrade to Spring Boot 2.7.7
- Upgrade dependencies
closes: #1798
> Upgrade to spring boot 2.7.7

- sechub-developertools/scripts/pds-api.sh
- sechub-developertools/scripts/sechub-api.sh
also:
- usage infos improved
- alive_check made working without credentials
closes: #1851
> Don't reveal secrets in the curl process #1851

- continous-integration-multibranch-pipeline.jenkins
> Feature 1876 fix git branch detection

- build.gradle
- gradle/libraries.gradle
- gradle/spring_boot_dependagen.gradle
* Upgrade to Spring Boot 2.7.8
* Upgrade dependencies
closes: #1882
> Feature 1882 upgrade to spring boot 2.7.8

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/networkpolicy.yaml
- k8s network policy added for external access
- chart version increased
closes #1885
> k8s network policy added for external access #1885

- MAINTAINERS.md
- company has been renamed
- imprint links updated
closes #1903
> update maintainers file #1903

- sechub-notification/src/main/java/com/mercedesbenz/sechub/domain/notification/user/NewApiTokenRequestedUserNotificationService.java
> Fix develop branch #1907

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
- sechub-storage-core/src/main/java/com/mercedesbenz/sechub/storage/core/S3Setup.java
- sechub-storage-s3-aws/src/main/java/com/mercedesbenz/sechub/storage/s3/AwsS3JobStorageFactory.java
- sechub-test/src/test/java/com/mercedesbenz/sechub/test/s3/S3RealLiveStorageManualTest.java
> Made many s3 client options configurable via spring values #1871

- sechub-pds-solutions/pds-base/docker/run.sh
> sleep time fixed #1918

- sechub-pds-solutions/scancode/docker/Scancode-Debian.dockerfile
- sechub-pds-solutions/scancode/docker/run_additional.sh
- sechub-pds-solutions/scancode/docker/scripts/scancode.sh
Fix small issues with Scancode + PDS solution
- Add `run_addtional.sh` script and execute `scancode --version` to see if there are issues with the installation.
closes: #1923
> Fix small issues with Scancode + PDS solution #1923

- sechub-solution/setup-pds-scripts/executors/owasp-zap.json
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/OwaspZapWrapperCLI.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/ZapWrapperExitCode.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContextFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapEventHandler.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/AbstractScan.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/util/EnvironmentVariableConstants.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/util/EnvironmentVariableReader.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapEventHandlerTest.java
> Implement Owasp Zap Wrapper handles cancel operation #1914

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context-initializer.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/help.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder_test.go
- sechub-developertools/scripts/sechub-api.sh
- works for getReport
- works for getStatus
- help texts updated
- also added funktionality to sechub-api.sh script
closes #545
> auto-get of latest jobUUID implemented #545

- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
> print jobUUID early #1603

- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/AbstractListDialogUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/ShowProductExecutorTemplatesDialogActionFactory.java
- sechub-pds-solutions/cloc/docker/cloc-Debian.dockerfile
- sechub-pds-solutions/cloc/docker/pds-config.json
- sechub-pds-solutions/cloc/env
This PR 
- closes #1937 
- closes #1967
> Final steps for CLOC #1937

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/help.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
Job listing implemented
- list size: 20 items
- some improvements for stage name readability
closes #367
> job listing implemented #367

- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
also improved a couple of comments
closes #1968
> sechub client recognizes canceled job #1968

- sechub-wrapper-owasp-zap/README.adoc
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/CommandLineSettings.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/OwaspZapScanExecutor.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/OwaspZapWrapperCLI.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/ZapWrapperExitCode.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContext.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContextFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/BaseTargetUriFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/IncludeExcludeToOwaspZapURLHelper.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapProductMessageHelper.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/OwaspZapURLType.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/AbstractScan.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/UnauthenticatedScan.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/auth/AbstractAuthScan.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/auth/HTTPBasicAuthScan.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/util/TargetConnectionChecker.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/OwaspZapScanExecutorTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanConfigurationFactoryTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContextFactoryTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/BaseTargetUriFactoryTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/helper/IncludeExcludeToOwaspZapURIHelperTest.java
- sechub-wrapper-owasp-zap/src/test/resources/sechub-config-examples/no-auth-include-exclude.json
> Implement improved connection checks

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/values.yaml
> Extend sechub-server helm chart with SecretScanner entries #1978

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/values.yaml
- S3 settings
- new scheduler strategy added
closes #2008
> server configuration extended #2008

- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetStartsWithURITargetResolveStrategy.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/TargetResolverService.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetStartsWithURITargetResolveStrategyTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/resolve/TargetResolverServiceTest.java
This PR
- closes #2017 
- closes #2018
> Feature 2018 multi uri target resolver strategies

- sechub-commons-pds/src/main/java/com/mercedesbenz/sechub/commons/pds/PDSConfigDataKeyProvider.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/action/config/ListExecutionProfilesDialogUI.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/SecHubProductExecutionPDSKeyProvider.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/ScanJobExecutionRunnable.java
- sechub-schedule/src/main/java/com/mercedesbenz/sechub/domain/schedule/access/ScheduleUserAccessToProjectValidationService.java
- typos/texts improved
- backticks scramble up the generated HTML (accents)
- docs: put examples as last information
closes #2020
> text improvements #2020

- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
> added handling for CANCELED #2041

- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetEndsWithURITargetResolveStrategy.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetIPpatternResolveStrategy.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetStartsWithURITargetResolveStrategy.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/TargetResolveStrategy.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetEndsWithURITargetResolveStrategyTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetIPpatternResolveStrategyTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/resolve/IntranetStartsWithURITargetResolveStrategyTest.java
- sechub-server/src/test/java/com/mercedesbenz/sechub/domain/scan/resolve/TargetResolverServiceSpringBootTest.java
- sechub-server/src/test/resources/application-test.properties
> Fix target resolving #2038

- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/scheduler/SchedulerAdministrationMessageHandler.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/scheduler/SchedulerStatusEntryKeys.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/MappingAdministrationRestControllerRestDocTest.java
- sechub-schedule/src/main/java/com/mercedesbenz/sechub/domain/schedule/job/SecHubJobRepository.java
- sechub-schedule/src/main/java/com/mercedesbenz/sechub/domain/schedule/status/SchedulerStatusService.java
- sechub-server/src/main/resources/db/migration/U21__delete_old_status_keys.sql
- sechub-server/src/main/resources/db/migration/V21__delete_old_adm_status_keys.sql
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/SchedulerMessage.java
- sechub-test/build.gradle
- sechub-test/src/test/java/com/mercedesbenz/sechub/domain/administration/SchedulerStatusEntryKeysTest.java
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/DomainAccessSourceVisitor.java
> Providing now all execution states in admin status #2039

- sechub-commons-model/build.gradle
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/JSONConverter.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/LocalDateTimeDeserializer.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/LocalDateTimeSerializer.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubDateTimeFormat.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubLocalDateTimeDeserializer.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubLocalDateTimeSerializer.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/JSONConverterTest.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionJobInQueueStatusEntry.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSJob.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/monitoring/PDSClusterMember.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/log/ProjectScanLog.java
This PR
- closes #1797 
- closes #2027
> Feature 1797 fix jsonconverter problems with localdate

- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/values.yaml
- sechub-pds-solutions/cloc/helm/pds-cloc/values.yaml
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/values.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/values.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/values.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/values.yaml
> improvements in Helm charts #2073

- CONTRIBUTING.md
- removed outdated email address
- wording improvements
closes #2091
> contribution docs improved #2091

- .github/workflows/create-pds-tools-release.yml
- .github/workflows/release-checkmarx-wrapper.yml
- .github/workflows/release-owaspzap-wrapper.yml
- missing creation of release issues added
- preparations for #1776 
closes #2107
> Extend actions workflows + prepare cx-wrapper separation #2107 #1776

- sechub-cli/src/mercedes-benz.com/sechub/util/archiveHelpers.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip_test.go
- sechub.json
- updated sechub.json with data section
- fixed exclude functionality for source code .zip files
closes #2122 
closes #2123
> Feature 2122 use data section

- .gitignore
- sechub-cli/src/mercedes-benz.com/sechub/util/tar.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar_test.go
> excludes work when creating .tar files #2127

- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example10_license_scan_with_sources_data_reference.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example11_license_scan_and_code_scan_with_sources_data_reference.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example13_secret_scan_with_binaries_data_reference.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example14_secret_scan_and_code_scan_with_sources_data_reference.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example8_web_scan_openapi_with_data_reference.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example9_license_scan_with_binaries_data_reference.json
> update sechub config examples inside the documentation #2120

- .github/workflows/create-pds-tools-release.yml
- .github/workflows/create-releases.yml
- .github/workflows/release-checkmarx-wrapper.yml
- .github/workflows/release-owaspzap-wrapper.yml
- apply-headers.sh
- test.sh
- ::set-output eliminated
- exclude list for `apply-headers.sh` improved
closes #1837
> update GitHub actions workflows #1837

- sechub-doc/helperscripts/publish+git-add-releasedocs.sh
> added sechub-getting-started.html to released documents #2087

- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/AbstractListDialogUI.java
> Sort tables in AbstractListDialogUI #2152

- sechub-developertools/scripts/sechub-api.sh
> enabled executor names for profile handling #2154

- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_metadata_example1.json
> fixes for labels documentation #2170

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidationError.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidationErrorTest.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario4/SecHubConfigurationFailuresScenario4IntTest.java
- sechub-server-core/src/main/java/com/mercedesbenz/sechub/server/core/ServerError.java
- sechub-server-core/src/main/java/com/mercedesbenz/sechub/server/core/ServerErrorController.java
- sechub-server-core/src/test/java/com/mercedesbenz/sechub/server/core/ServerErrorControllerTest.java
This PR
- closes #2172 
- closes #2185 
- closes #2186
> Handle multiple problems with server validation reponse

- build.gradle
- gradle/libraries.gradle
- gradle/spring_boot_dependagen.gradle
- gradle/wrapper/gradle-wrapper.properties
- upgrade to Spring Boot 2.7.11
- upgrade to Gradle 8.1.1
- upgrade dependencies
> Feature 2192 upgrade to spring boot 2.7.11

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/AbstractScan.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/auth/AbstractAuthScan.java
> Make sure includes are known to OWASP ZAP #2160

- .github/workflows/create-pds-tools-release.yml
- .github/workflows/create-releases.yml
- .github/workflows/gradle.yml
- .github/workflows/publish-libraries.yml
- .github/workflows/release-checkmarx-wrapper.yml
- .github/workflows/release-owaspzap-wrapper.yml
- continous-integration-multibranch-pipeline.jenkins
- gradle/build-java.gradle
- release-pipeline.jenkins
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/job/JobInformationRepositoryDBTest.java
- sechub-doc/src/docs/asciidoc/documents/config.adoc
- sechub-doc/src/docs/asciidoc/documents/operations/server/server_deployment.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/launchconfig/launchconfig_common_dev_adminui_header.adoc
- sechub-doc/src/docs/asciidoc/documents/techdoc/01_development.adoc
- sechub-doc/src/docs/asciidoc/sechub-developer-quickstart-guide.adoc
- sechub-pds-solutions/pds-base/docker/PDS-Debian.dockerfile
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/job/PDSJobRepositoryDBTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/log/ProjectScanLogRepositoryDBTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/product/ProductResultRepositoryDBTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/report/ScanReportRepositoryDBTest.java
- sechub-schedule/src/test/java/com/mercedesbenz/sechub/domain/schedule/job/SecHubJobRepositoryDBTest.java
- sechub-solution/docker/SecHub-Alpine.dockerfile
- sechub-solution/docker/SecHub-Debian.dockerfile
- sechub-solution/docker/SecHub-Fedora.dockerfile
- sechub-solution/docker/SecHub-Rocky.dockerfile
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/FlakyOlderThanTestWorkaround.java
This PR 
- closes #1736
- closes #2213 
- closes #2203
> Feature 1736 upgrade to java 17

- .github/workflows/create-releases.yml
- .github/workflows/gradle.yml
- sechub-doc/src/docs/asciidoc/documents/config.adoc
- sechub-doc/src/docs/asciidoc/sechub-developer-quickstart-guide.adoc
- sechub-pds-solutions/gosec/docker/GoSec-Debian.dockerfile
- sechub-pds-solutions/pds-base/docker/PDS-Debian.dockerfile
- sechub-pds-solutions/pds-base/env
> Upgrade to Golang 1.20.4 #2220

- github-actions/scan/README.adoc
- github-actions/scan/action.yml
> SecHub Github action: Fix documention and upgrade used client #2189

- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
> fixed column length #2223

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertReport.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/IntegrationTestJSONLocation.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario20/PDSSecretScanJobScenario20IntTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario3/FalsePositivesScenario3IntTest.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/AbstractSourceCodeBasedFalsePositiveStrategy.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/CodeScanFalsePositiveStrategy.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SecretScanFalsePositiveStrategy.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoFalsePositiveFinder.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoFalsePositiveMarker.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoFalsePositiveStrategy.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoFalsePositiveSupport.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/WebScanFalsePositiveStrategy.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/CodeScanFalsePositiveStrategyTest.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SecretScanFalsePositiveStrategyTest.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoFalsePositiveFinderTest.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoFalsePositiveSupportTest.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/TestSerecoVulnerabilityBuilder.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/WebScanFalsePositiveStrategyTest.java
- sechub-scan-product-sereco/src/test/resources/false_positives/scan_false_positive_config_example5.json
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveMetaDataFactory.java
- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/importer/SarifV1JSONImporter.java
- sechub-sereco/src/test/java/com/mercedesbenz/sechub/sereco/importer/SarifV1JSONImporterTest.java
This PR
- closes #2226 
- closes #2028
- closes #2016
> Secret scan FP handling, allow empty CWE IDs and provide CWE 798 as secret scan SARIF import fallback #2226, #2028

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
> client action validation improved #2195

- sechub-doc/src/docs/asciidoc/sechub-developer-quickstart-guide.adoc
> Add MacOS documentation #2247

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario4/SecHubConfigurationFailuresScenario4IntTest.java
- sechub-server-core/src/main/java/com/mercedesbenz/sechub/server/core/SecHubExceptionHandler.java
> Custom bad request handling for Jackson exceptions #2250

- README.adoc
Change link to getting started guide
closes: #2242
> Change link to getting started guide #2242

- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/job/JobCancelService.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/job/JobInformation.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/job/JobInformationCreateService.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/job/JobRestartRequestService.java
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/job/JobInformationCreateServiceTest.java
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/job/JobInformationRepositoryDBTest.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/JobAdministrationRestControllerRestDocTest.java
- sechub-server/src/main/resources/db/migration/U24__drop_and_recreate_adm_jobinformation_tables.sql
- sechub-server/src/main/resources/db/migration/V24__drop_and_recreate_adm_jobinformation_tables.sql
> Avoid duplicated administrative job information entities by changing primary key and logic

- sechub-storage-s3-aws-test/src/test/java/com/mercedesbenz/sechub/storage/s3/AwsS3JobStorageTest.java
- sechub-storage-s3-aws/src/main/java/com/mercedesbenz/sechub/storage/s3/AwsS3JobStorage.java
- sechub-storage-s3-aws/src/main/java/com/mercedesbenz/sechub/storage/s3/DefaultTransferManagerFactory.java
- sechub-storage-s3-aws/src/main/java/com/mercedesbenz/sechub/storage/s3/TransferManagerFactory.java
This PR
- closes #1779 
- closes #2269
> Improved S3 error handling and fixed log messages

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSWorkspaceService.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/job/PDSWorkspaceServiceTest.java
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/PDSTestURLBuilder.java
> Changed PDS workspace location handling #2255

- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/AdministrationAPIConstants.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserAdministrationRestController.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserDetailInformationService.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserRepository.java
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/UserRepositoryDBTest.java
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/user/UserAdministrationRestControllerMockTest.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/DeveloperAdministration.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/action/user/ShowUserDetailForEmailAddressAction.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/UserAdministrationRestControllerRestDocTest.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/UseCaseIdentifier.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/admin/user/UseCaseAdminShowsUserDetailsForEmailAddress.java
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/SecHubTestURLBuilder.java
> Implemented fetch user details by email address #1095

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionService.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSJob.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSJobRepository.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/job/PDSJobTransactionService.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionServiceTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/job/PDSJobRepositoryDBTest.java
> Introduce continuous deployment for PDS #2273

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/IntegrationTestDefaultExecutorConfigurations.java
- sechub-integrationtest/src/main/resources/pds-config-integrationtest.json
- sechub-pds-solutions/checkmarx/docker/pds-config.json
- sechub-wrapper-checkmarx/src/main/java/com/mercedesbenz/sechub/wrapper/checkmarx/cli/CheckmarxWrapperEnvironment.java
- sechub-wrapper-checkmarx/src/main/java/com/mercedesbenz/sechub/wrapper/checkmarx/cli/CheckmarxWrapperKeyConstants.java
- sechub-wrapper-checkmarx/src/main/java/com/mercedesbenz/sechub/wrapper/checkmarx/cli/CheckmarxWrapperKeys.java
- sechub-wrapper-checkmarx/src/main/java/com/mercedesbenz/sechub/wrapper/checkmarx/scan/CheckmarxWrapperScanService.java
- sechub-wrapper-checkmarx/src/test/java/com/mercedesbenz/sechub/wrapper/checkmarx/scan/CheckmarxWrapperScanServiceTest.java
> Changed pds checkmarx period check to milliseconds #2278

- sechub-pds-solutions/pds-base/docker/run.sh
> Feature 2284 pds base enable graceful shutdown

- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/templates/deployment.yaml
- sechub-pds-solutions/cloc/helm/pds-cloc/templates/deployment.yaml
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/templates/deployment.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/multi/helm/pds-multi/templates/deployment.yaml
- sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/templates/deployment.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/templates/deployment.yaml
> Helm indentation fixed #2302

- .github/workflows/_build+publish-pds-solution.yml
- .github/workflows/_build+publish-pds-solutions.yml
- .github/workflows/build+publish-all-pds-solutions.yml
- .github/workflows/release-client-server-pds.yml
> Feature #1936 release: build + push container images

- continous-integration-multibranch-pipeline.jenkins
> Fixed Jenkins builds #2346

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/help.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
also docs updated
closes #2351
> made help and version to actions only #2351

- sechub-doc/src/docs/asciidoc/documents/pds/about_pds.adoc
- sechub-doc/src/docs/asciidoc/documents/pds/pds_config.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/pds_options.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/sechub_options.adoc
Especially described Docker and Kubernetes parts.
closes #2348
> pds documentation improved #2348

- github-actions/scan/README.adoc
- github-actions/scan/action.yml
- github-actions/scan/dist/index.js
- github-actions/shared/src/sechub-cli.ts
> Feature 2349 make sechub scan action use 32 bit client

- docs/index.html
Update information at documentation main page
closes: https://github.com/mercedes-benz/sechub/issues/2360
> Update information at documentation main page #2360

- sechub-doc/src/docs/asciidoc/sechub-getting-started.adoc
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSProductExecutorKeyConstants.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/SecHubProductExecutionPDSKeyProvider.java
- sechub-solution/setup-pds/executors/bandit.json
- sechub-solution/setup-pds/executors/checkmarx-and-gosec/checkmarx-filtered.json
- sechub-solution/setup-pds/executors/checkmarx-and-gosec/gosec-filtered.json
- sechub-solution/setup-pds/executors/checkmarx.json
- sechub-solution/setup-pds/executors/checkmarx_mock.json
- sechub-solution/setup-pds/executors/cloc.json
- sechub-solution/setup-pds/executors/findsecuritybugs.json
- sechub-solution/setup-pds/executors/flawfinder.json
- sechub-solution/setup-pds/executors/gitleaks.json
- sechub-solution/setup-pds/executors/gosec.json
- sechub-solution/setup-pds/executors/mobsfscan.json
- sechub-solution/setup-pds/executors/njsscan.json
- sechub-solution/setup-pds/executors/owasp-zap.json
- sechub-solution/setup-pds/executors/pmd.json
- sechub-solution/setup-pds/executors/scancode.json
- sechub-solution/setup-pds/executors/tern.json
- sechub-solution/setup-pds/executors/tern_mock.json
> Renamed PDS product executor configuration entries on SecHub side #2377

- gradle/build-spring.gradle
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/config/PDSSummaryLogService.java
- sechub-pds/src/main/resources/banner.txt
- sechub-server/src/main/resources/banner.txt
> Added banners for PDS and SecHub and improved PDS summary #2026

- SECURITY.md
> Update link in Security.md #2392

- sechub-pds-solutions/owaspzap/env
> Update OWASP ZAP to 2.13.0 #2389

- sechub-pds-solutions/cloc/helm/pds-cloc/Chart.yaml
- sechub-pds-solutions/cloc/helm/pds-cloc/templates/deployment.yaml
> limit db connections #2404

- sechub-pds-solutions/cloc/helm/pds-cloc/Chart.yaml
- sechub-pds-solutions/cloc/helm/pds-cloc/templates/deployment.yaml
> enable write acces to mounted volumes #2407

- sechub-server/src/main/resources/db/migration/U25__enlarge_data_fields.sql
- sechub-server/src/main/resources/db/migration/V25__enlarge_data_fields.sql
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/validation/ProjectIdValidationImpl.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/validation/UserIdValidationImpl.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/validation/ProjectIdValidationImplTest.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/validation/UserIdValidationImplTest.java
- closes #1627 
- closes #1626
> Feature 1627 increase field length

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/config/PDSProductIdentifierValidator.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/config/PDSProductIdentifierValidatorTest.java
- closes #1273 
- closes #2411
> Enlarge PDS product ID + handle alphabetic validation #1273 #2411

- sechub-pds-solutions/checkmarx/10-create-image.sh
> pds-cx: made builder base image configurable #2410

- sechub-cli/build_go.sh
Build of SecHub client: force static linking (also done some rework/streamlining of the code)
closes #2416
> Always link sechub client statically #2416

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
> Feature 2421 server helm chart fix

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
removed unnecessary code which produced the error
closes #2418
> help action fixed #2418

- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxAdapter.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxAdapterV1.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/CheckmarxProjectSupport.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/CheckmarxScanReportSupport.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/CheckmarxScanSupport.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/CheckmarxUploadSupport.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/WaitForQueueStateSupport.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/WaitForScanReportSupport.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/WaitForScanStateSupport.java
> Introduce constant and rename log messages accordingly #2415

- sechub-storage-s3-aws-test/README.md
- sechub-storage-s3-aws-test/src/test/java/com/mercedesbenz/sechub/storage/s3/AwsS3JobStorageTest.java
- sechub-storage-s3-aws/src/main/java/com/mercedesbenz/sechub/storage/s3/AwsS3JobStorage.java
- sechub-storage-sharedvolume-spring/src/main/java/com/mercedesbenz/sechub/storage/sharevolume/spring/SharedVolumeJobStorage.java
> Enhanced logging for S3 and NFS storage + documentation changes #2430

- sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/WithSecHubClient.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario12/PDSWebScanJobScenario12IntTest.java
> Fix HTML escaping + integration test now uses client #2442

- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
> client: labels documentation improved #2444

- .github/workflows/github-action-scan.yml
> Provide a CI/CD workflow for GitHub action #2449

- sechub-pds-solutions/owaspzap/docker/Owasp-Zap-Debian.dockerfile
- sechub-pds-solutions/owaspzap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owaspzap/helm/pds-owaspzap/templates/deployment.yaml
> made .ZAP writeable for pds user #2459

- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/AbstractPDSProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSAnalyticsExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSCodeScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSExecutorConfigSupport.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSInfraScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSLicenseScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSSecretScanProductExecutor.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSStorageContentProvider.java
- sechub-scan-product-pds/src/main/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSWebScanProductExecutor.java
- sechub-scan-product-pds/src/test/java/com/mercedesbenz/sechub/domain/scan/product/pds/PDSExecutorConfigSupportTest.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/product/AbstractProductExecutor.java
> Feature 2467 sechub calls pds only when it makes sense

- .github/workflows/release-client-server-pds.yml
- .github/workflows/release-pds-tools.yml
- sechub-api-java/src/main/resources/.gitignore
> restore reduced-openapi3.json before check #2490

- sechub.json
> test dirs excluded #2494

- sechub-solution/docker/SecHub-Debian.dockerfile
- sechub-solution/docker/SecHub-Rocky.dockerfile
- sechub-solution/env
> build: same Go version (1.20.4) everywhere #2515

- MAINTAINERS.md
Added myself to MAINTAINERS.md
> Added new contributor #2530

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/helper/IncludeExcludeToZapURLHelper.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/helper/IncludeExcludeToZapURLHelperTest.java
> Improve include/exclude handling #2542

- sechub-api-java/README.adoc
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/AbstractSecHubClient.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/DefaultSecHubClient.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/ExecutionProfile.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/Job.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/JobStatus.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/MockedSecHubClient.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/SecHubClient.java
- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/User.java
- sechub-api-java/src/test/java/com/mercedesbenz/sechub/api/MockedSecHubClientTest.java
- sechub-api-java/src/test/java/com/mercedesbenz/sechub/api/generator/InternalAccessModelFileGenerator.java
- sechub-api-java/src/test/java/com/mercedesbenz/sechub/api/generator/PublicModelFileGenerator.java
- sechub-examples/example-sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/java/demo/OpenAPITestTool.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/SystemTestRuntimeContext.java
> Change SecHubClient to interface with two implementations #2533

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ApiDefinitionFileProvider.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContext.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/config/ApiDefinitionFileProviderTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactoryTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
> Improve handling of data section inside ZAP wrapper application

- sechub-pds-solutions/owaspzap/env
> Update wrapper release version #2567

- sechub-commons-archive/src/main/java/com/mercedesbenz/sechub/commons/archive/ArchiveSupport.java
> Use posix mode for big numbers in TAR archives #2569

- sechub-doc/src/docs/asciidoc/documents/techdoc/03_coding_conventions.adoc
- sechub-server/src/main/resources/db/migration/U26__statistic_indices.sql
- sechub-server/src/main/resources/db/migration/V26__statistic_indices.sql
> Feature 2574 indices on statistic tables

- sechub-api-java/src/main/java/com/mercedesbenz/sechub/api/DefaultSecHubClient.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/SystemTestRuntimeContext.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/CurrentTestVariableCalculatorFactory.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestAssertion.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngine.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/TestRuntimeAccess.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngineTest.java
> Enhanced error handling in system test runtime #2561

- sechub-integrationtest/pds/product-scripts/integrationtest-codescan.sh
- sechub-integrationtest/pds/product-scripts/shared/shared-events.sh
- sechub-integrationtest/pds/product-scripts/shared/shared-merging.sh
> Feature 2577 avoid ambigous redirect errors in bash scripts

- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario1/AutoCleanupScenario1IntTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario3/FalsePositivesScenario3IntTest.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/autocleanup/ScanAutoCleanupService.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveJobDataConfigMerger.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveJobDataService.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/autocleanup/ScanAutoCleanupServiceTest.java
This PR
- closes #2075 
- closes #2076
> Enable auto cleanup for old scan reports #2075

- sechub-pds-solutions/multi/docker/Multi-Debian.dockerfile
- sechub-pds-solutions/multi/docker/mocks/bandit_mock.sarif.json
- sechub-pds-solutions/multi/docker/packages.txt
closes #2556 
Currently the CWE Sarif Plugin is located at my personal repository and will be fetched in the docker build https://github.com/alexdd/bandit-sarif-formatter
> Feature 2556: Integrate cwe extended bandit sarif formatter plugin into pds-solutions

- sechub-doc/src/docs/asciidoc/documents/shared/systemtests/systemtests.adoc
- sechub-pds-tools/src/main/java/com/mercedesbenz/sechub/pds/tools/SystemTestCommand.java
- sechub-pds-tools/src/main/java/com/mercedesbenz/sechub/pds/tools/systemtest/SystemTestLauncher.java
- sechub-pds-tools/src/test/java/com/mercedesbenz/sechub/pds/tools/PDSToolsCLITest.java
- sechub-pds-tools/src/test/java/com/mercedesbenz/sechub/pds/tools/systemtest/SystemTestLauncherTest.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/SystemTestAPI.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/SystemTestParameters.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/config/TestDefinition.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/SystemTestRuntime.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/SystemTestRuntimeContext.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/error/SystemTestFailure.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/init/SystemTestRuntimePreparator.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngine.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/SystemTestDryRunTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/config/SystemTestConfigurationTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/SystemTestRuntimeContextTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/SystemTestRuntimePreparatorTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngineTest.java
This PR
- closes #2596 
- closes #2594 
- closes #2593 
- closes #2497
- closes #2605
> Feature 2594 fix and enhance systemtest framework

- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/admin/FullScanDataRestController.java
> Changed content type for full scan log REST to "application/zip" #2608

- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContext.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/helper/IncludeExcludeToZapURLHelper.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/util/TargetConnectionChecker.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/util/UrlUtil.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactoryTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/helper/IncludeExcludeToZapURLHelperTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/UrlUtilTest.java
- sechub-wrapper-owasp-zap/src/test/resources/sechub-config-examples/no-auth-include-exclude.json
- sechub-wrapper-owasp-zap/src/test/resources/sechub-config-examples/no-auth-without-includes-or-excludes.json
- closes #2555 
I extended the documentation so it is more clear how this will work. If I got anything wrong about the intended behavior please let me know.
> Feature 2555 zap wrapper handle includes excludes wildcards

- .github/workflows/release-pds-tools.yml
- buildSrc/src/main/groovy/VersionData.groovy
- gradle/build-versioning.gradle
> Added debug info in case assert fails #2620

- continous-integration-multibranch-pipeline.jenkins
> Feature 2618 update jenkins file

- build.gradle
- buildSrc/src/main/groovy/VersionData.groovy
- gradle/build-maven.gradle
- gradle/build-versioning.gradle
- sechub-cli/build.gradle
- sechub-doc/build.gradle
- sechub-integrationtest/build.gradle
- sechub-pds-tools/build.gradle
- sechub-pds/build.gradle
- sechub-server/build.gradle
- sechub-systemtest/build.gradle
- sechub-wrapper-checkmarx/build.gradle
- sechub-wrapper-owasp-zap/build.gradle
> Replaced static variables by version data object #2625

- sechub-developertools/scripts/sechub-api.sh
> sechub-api.sh: improve handling of non-existent projects #2642

- sechub-cli/script/supported-source-extensions.txt
The file extensions for Lua and Rust has been added.
closes #2654
> Added Rust and Lua to supported fileextension

- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxAdapterV1.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/CheckmarxOnlyUnsupportedFilesException.java
- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/support/CheckmarxScanSupport.java
- sechub-adapter-checkmarx/src/test/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxAdapterV1WireMockTest.java
- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/Workspace.java
- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/importer/ImportSupport.java
- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/importer/ProductImportAbility.java
- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/importer/integrationtest/IntegrationTestPDSCWebScanImporter.java
- sechub-sereco/src/main/java/com/mercedesbenz/sechub/sereco/importer/integrationtest/IntegrationTestPDSCodeScanImporter.java
- sechub-sereco/src/test/java/com/mercedesbenz/sechub/sereco/importer/ImportSupportTest.java
- sechub-sereco/src/test/java/com/mercedesbenz/sechub/sereco/importer/SarifV1JSONImporterTest.java
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/WiremockUrlHistory.java
This PR
- closes #2652
- closes #2656
- closes #2661
> Enhance CheckmarxAdapterV1

- sechub-api-java/src/main/resources/reduced-openapi3.json
- sechub-commons-model-testframework/src/main/java/com/mercedesbenz/sechub/commons/model/TestSecHubConfigurationBuilder.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubWebScanConfiguration.java
- sechub-doc/openapi-workaround.gradle
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/SchedulerRestControllerRestDocTest.java
> Add restdoc test for webscan with openApi defintion #2663

- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoReportProductExecutor.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoReportProductExecutorTest.java
> Fixed Sereco missing timestamps in product results #2666

- sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go
> removed unecessary request headers #2466

- .github/workflows/documentation-build.yml
needed for testing while developing "Documentation build" action
> initial action for documentation builds #2285

- .github/workflows/gradle.yml
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/TestAPI.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario10/PDSCodeScanSarifJobScenario10IntTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario2/SecHubExecutionScenarioSecHubClientIntTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario20/PDSSecretScanJobScenario20IntTest.java
> Storing now test reports for webscan, secretscan and codescan #2680

- .github/workflows/_build+publish-pds-solution.yml
- .github/workflows/documentation-build.yml
- .github/workflows/github-action-scan.yml
- .github/workflows/gradle.yml
- .github/workflows/publish-libraries.yml
- .github/workflows/release-client-server-pds.yml
- .github/workflows/release-pds-tools.yml
- .github/workflows/release-wrapper-checkmarx.yml
- .github/workflows/release-wrapper-owaspzap.yml
> Security: pinned 3rd party GitHub actions to commit hash instead of version tag #2665

- sechub-pds-solutions/checkmarx/env
> Use latest Checkmarx wrapper 1.2.0 in builds #2695

- sechub-cli/script/supported-source-extensions.txt
> client: support certificates in scans for secrets #2698

- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/ArtifactStorageSecHubClientListener.java
- sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngine.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngineTest.java
> Systemtest sechub config file is now written direct after creation #2715

- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidatorTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/SystemTestDryRunTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/config/SystemTestConfigurationTest.java
- sechub-systemtest/src/test/resources/fake-root/sechub-pds-solutions/faked-xray/05-start-single-sechub-network-docker-compose.sh
- sechub-systemtest/src/test/resources/fake-root/sechub-pds-solutions/faked-xray/05-stop-single-sechub-network-docker-compose.sh
- sechub-systemtest/src/test/resources/fake-root/sechub-pds-solutions/faked-xray/docker/pds-config.json
- sechub-systemtest/src/test/resources/fake-root/sechub-solution/01-start-single-docker-compose.sh
- sechub-systemtest/src/test/resources/systemtest_xray_licensescan_example.json
> Added unit tests and dry-run system tests for xray #2713

- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidatorTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/SystemTestDryRunTest.java
- sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/config/SystemTestConfigurationTest.java
> Applied spotless #2724

- sechub-doc/src/docs/asciidoc/sechub-getting-started.adoc
* Updated the requirements section
* Added section which installs the client
closes #2745
> Added sechub client installation

- sechub-api-java/build.gradle
> Introduce gradle task buildJavaApiAll

- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/AbstractSourceCodeBasedFalsePositiveStrategy.java
- sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoSourceRelevantPartResolver.java
- sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/AbstractSourceCodeBasedFalsePositiveStrategyTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/project/FalsePositiveMetaDataFactoryTest.java
> Improved false-positive handling for missing end elements #2754

- sechub-doc/src/docs/asciidoc/documents/techdoc/03_coding_conventions.adoc
> yaml template coding convention updated #2774

- sechub-pds-solutions/iac/helm/pds-iac/templates/deployment.yaml
> Fixed typo in deployment.yaml

- .github/workflows/_build+publish-pds-solution.yml
- .github/workflows/build+publish-all-pds-solutions.yml
- .github/workflows/release-wrapper-xray.yml
- sechub-pds-solutions/xray/09-compute-image-tag.sh
- sechub-pds-solutions/xray/10-create-image.sh
- sechub-pds-solutions/xray/docker/Xray-Debian.dockerfile
- sechub-pds-solutions/xray/docker/copy/README.adoc
- sechub-pds-solutions/xray/env
- sechub-pds-solutions/xray/helm/pds-xray/LICENSE
> Feature 2762 pds xray release and build part2

- .github/workflows/build+publish-all-pds-solutions.yml
- sechub-pds-solutions/iac/09-compute-image-tag.sh
- sechub-pds-solutions/loc/09-compute-image-tag.sh
- sechub-pds-solutions/multi/09-compute-image-tag.sh
> Feature 2779 pds iac prepare build+publish

- sechub-pds-solutions/gitleaks/tests/README.adoc
- sechub-pds-solutions/gitleaks/tests/clone_repo.sh
- sechub-pds-solutions/gitleaks/tests/copy_sanitycheck_files.sh
- sechub-pds-solutions/gitleaks/tests/sanity-check-testdata/my-readme.md
- sechub-pds-solutions/iac/tests/README.adoc
- sechub-pds-solutions/iac/tests/clone_repo.sh
- sechub-pds-solutions/iac/tests/copy_sanitycheck_files.sh
- sechub-pds-solutions/iac/tests/sanity-check-testdata/Dockerfile
- sechub-pds-solutions/iac/tests/systemtest_local_kics.json
- add wrong secrets and sanity check to GitLeaks test suite
- add system tests for Kics #2771
> New system tests for Kics and GitLeaks #2771

- sechub-doc/src/docs/asciidoc/documents/tutorials/01_tutorials.adoc
- sechub-doc/src/docs/asciidoc/documents/tutorials/02_integrate_new_module.adoc
- sechub-doc/src/docs/asciidoc/documents/tutorials/03_create_new_pds_solution.adoc
- sechub-doc/src/docs/asciidoc/sechub-tutorials.adoc
> Increased section numeration in tutorial #2797

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/templates/networkpolicy.yaml
- sechub-solution/helm/sechub-server/templates/service.yaml
- sechub-solution/helm/sechub-server/values.yaml
- closes #2816 
- closes #2815
> Feature 2816 enhance server helm chart #2816

- sechub-commons-archive/src/main/java/com/mercedesbenz/sechub/commons/archive/SecHubFileStructureDataProviderBuilder.java
- sechub-commons-archive/src/test/java/com/mercedesbenz/sechub/commons/archive/SecHubFileStructureDataProviderBuilderTest.java
>  Fix client certificate data section not extracted #2822

- sechub-pds-solutions/owaspzap/docker/Owasp-Zap-Debian.dockerfile
> Remove unnecessary downloads content #2813

- .github/workflows/gradle.yml
> Changed ordering to enforce normal integration tests run always #2853

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
> Go Client: Make action and options case agnostic #2858

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/false-positives.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/false-positives_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/help.go
- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
- closes #2077 
- closes #2862
> client: defineFalsePositives feature #2077

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context-initializer.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context-initializer_test.go
- used to throw a 401; now fixed
- test added for the same
- closes #2861
> username case correction works with getReport #2861

- sechub-solution/setup-pds/8800-setup-project-and-user.sh
- sechub-solution/setup-pds/8801-create-executor-and-profile.sh
- sechub-solution/setup-pds/8802-assign-profile-to-project.sh
- sechub-solution/setup-pds/8900-helper.sh
- sechub-solution/setup-pds/8901-check-setup.sh
- sechub-solution/setup-pds/setup-bandit.sh
- sechub-solution/setup-pds/setup-checkmarx-mock.sh
- sechub-solution/setup-pds/setup-checkmarx.sh
- sechub-solution/setup-pds/setup-cloc.sh
- sechub-solution/setup-pds/setup-findsecuritybugs.sh
- sechub-solution/setup-pds/setup-flawfinder.sh
- sechub-solution/setup-pds/setup-gitleaks.sh
- sechub-solution/setup-pds/setup-gosec.sh
- sechub-solution/setup-pds/setup-kics.sh
- sechub-solution/setup-pds/setup-mobsfscan.sh
- sechub-solution/setup-pds/setup-njsscan.sh
- sechub-solution/setup-pds/setup-owasp-zap.sh
- sechub-solution/setup-pds/setup-pmd.sh
- sechub-solution/setup-pds/setup-scancode.sh
- sechub-solution/setup-pds/setup-tern-mock.sh
- sechub-solution/setup-pds/setup-tern.sh
- sechub-solution/setup-pds/setup-xray-mock.sh
- sechub-solution/setup-pds/setup-xray.sh
> Added comments to shell scripts #2824

- gradle/projects.gradle
> Added sechub-wrapper-xray to eclipse Projects #2838

- sechub-pds-solutions/iac/helm/pds-iac/Chart.yaml
- sechub-pds-solutions/iac/helm/pds-iac/templates/deployment.yaml
- sechub-pds-solutions/iac/helm/pds-iac/values.yaml
> deploymentComment + templateMetadataAnnotations added #2895

- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/logging/BasicAuthUserExtraction.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/logging/DefaultSecurityLogService.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/logging/SecurityLogData.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/logging/BasicAuthUserExtractionTest.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/logging/DefaultSecurityLogServiceTest.java
> Username now always extracted from BasicAuth added to security log #2907

- CONTRIBUTING.md
- README.adoc
- sechub-doc/src/docs/asciidoc/documents/techdoc/04_documentation.adoc
- merged wiki information into CONTRIBUTING.md
- updated top level readme.adoc
- improved docs for documentation
- closes #2925
> Feature 2925 update contributions docs

- sechub-pds-solutions/gitleaks/env
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/.helmignore
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/Chart.yaml
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/LICENSE
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/README.md
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/templates/deployment.yaml
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/templates/networkpolicy.yaml
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/templates/service.yaml
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/values.yaml
- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/values.yaml
- Helm chart for pds-gitleaks
- server integration of pds-gitleaks
- closes #2944
> Feature 2944 gitleaks integration

- sechub-solution/env
> fix docker-compose script #2953

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/AbstractSecHubFileSystemContainer.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubBinaryDataConfiguration.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelReducedCloningSupport.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubRemoteContainer.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubRemoteDataConfiguration.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubSourceDataConfiguration.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubScanConfigurationTest.java
- sechub-commons-model/src/test/resources/sechub_remote_data_config_binary_code_scan_example.json
- sechub-commons-model/src/test/resources/sechub_remote_data_config_source_code_scan_example.json
- sechub-integrationtest/pds/product-scripts/integrationtest-prepare.sh
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/IntegrationTestDefaultExecutorConfigurations.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/IntegrationTestDefaultProfiles.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/scenario22/Scenario22.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario22/PDSPrepareIntegrationScenario22IntTest.java
- sechub-integrationtest/src/test/resources/sechub-integrationtest-remote-scan-configuration.json
> Extended SecHub commons-core model

- .github/workflows/release-client-server-pds.yml
- .github/workflows/release-pds-tools.yml
- .github/workflows/release-wrapper-checkmarx.yml
- .github/workflows/release-wrapper-owaspzap.yml
- .github/workflows/release-wrapper-xray.yml
- sechub-webui/build.gradle
> add versioning to webui build #2989

- sechub-pds-solutions/owaspzap/docker/pds-config.json
- sechub-pds-solutions/owaspzap/docker/scripts/owasp-zap.sh
> Enable administrator to pass JVM ARGS to ZAP #3003

- sechub-commons-core/src/main/java/com/mercedesbenz/sechub/commons/core/util/SimpleStringUtils.java
- sechub-commons-core/src/test/java/com/mercedesbenz/sechub/commons/core/util/SimpleStringUtilsTest.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/ScanReportRestControllerRestDocTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario20/PDSSecretScanJobScenario20IntTest.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/report/DownloadScanReportService.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/report/ScanReportRestController.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/report/ScanReportSensitiveDataObfuscator.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/ScanReportRestControllerMockTest.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/report/ScanReportSensitiveDataObfuscatorTest.java
> Obfuscate secret scan findings in reports

- sechub-pds-solutions/gitleaks/docker/Gitleaks.dockerfile
- sechub-pds-solutions/gitleaks/docker/custom-gitleaks.toml
- sechub-pds-solutions/gitleaks/docker/scripts/gitleaks.sh
> Feature 3049 add custom rule file to pds gitleaks

- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
> Update and clarify webscan config form based auth example #3047

- docs/index.html
> Mentioned IDE plugins in docs #721

- sechub-cli/src/mercedes-benz.com/sechub/cli/context.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/tarbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/tarbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/testutil/asserts.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip.go
> client accepts remote-data-section #2976

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubRemoteCredentialConfiguration.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubRemoteCredentialData.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubRemoteCredentialUserData.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubRemoteDataConfiguration.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubScanConfigurationTest.java
- sechub-commons-model/src/test/resources/sechub_remote_data_config_binary_code_scan_example.json
- sechub-commons-model/src/test/resources/sechub_remote_data_config_source_code_scan_example.json
> Added credentials to remote sechub configuration

- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig_test.go
> Feature 3078 client secrets scan switches off filtering

- sechub-pds-solutions/gitleaks/docker/scripts/gitleaks.sh
> improved message to user to clarify scanning behaviour #3120

- .github/workflows/github-action-scan.yml
- github-actions/scan/README.adoc
- github-actions/scan/__test__/integrationtest.test.ts
- github-actions/scan/action.yml
- github-actions/scan/package-lock.json
- github-actions/scan/package.json
> Gha feature default to client 1.5.0 v2  #3117

- sechub-developertools/scripts/sechub-api.sh
> improved anonymous calls #3137

- .github/workflows/documentation-build.yml
- .github/workflows/gradle.yml
- .github/workflows/publish-libraries.yml
- .github/workflows/release-client-server-pds.yml
- .github/workflows/release-pds-tools.yml
- .github/workflows/release-webui.yml
- .github/workflows/release-wrapper-checkmarx.yml
- .github/workflows/release-wrapper-owaspzap.yml
- .github/workflows/release-wrapper-xray.yml
> switch to renamed gradle action #3083

- github-actions/scan/__test__/input-helper.test.ts
- github-actions/scan/__test__/report-format.test.ts
- github-actions/scan/src/input-helper.ts
- github-actions/scan/src/launcher.ts
- github-actions/scan/src/projectname-resolver.ts
- github-actions/scan/src/report-formats.ts
- closes:  #3143
note: The `createSafeBuilderData` method of the `launcher.ts` component is a candidate for testing, but since it's not exposed as a public function it's not accessible from outside. Testing it through the `launch` method call would be complex for the sake of this pull request. 
We might consider to refactor the `launcher.ts` component in the future.
> sanitize github actions input strings #3143

- github-actions/scan/__test__/integrationtest/01-start.sh
- github-actions/scan/__test__/integrationtest/03-init_sechub_data.sh
- github-actions/scan/__test__/integrationtest/05-stop.sh
- github-actions/scan/__test__/integrationtest/start_pds.sh
- github-actions/scan/__test__/integrationtest/start_sechub_server.sh
- github-actions/scan/__test__/integrationtest/stop_pds.sh
- github-actions/scan/__test__/integrationtest/stop_sechub_server.sh
- github-actions/scan/__test__/integrationtest/wait_server_alive.sh
- github-actions/scan/package-lock.json
- github-actions/scan/package.json
- github-actions/scan/src/client-download.ts
- github-actions/scan/src/fs-helper.ts
- github-actions/scan/src/launcher.ts
- github-actions/scan/src/platform-helper.ts
- github-actions/scan/src/sechub-cli.ts
> make github actions integration test platform independent #3148

- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/false-positives.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/false-positives_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/report.go
- sechub-cli/src/mercedes-benz.com/sechub/util/errorhandler.go
> Client: Perform send requests to mark false positives in chunks if needed #3122

- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig_test.go
> fixed licenseScan having an empty zip file #3178

- github-actions/scan/__test__/integrationtest.test.ts
- github-actions/scan/__test__/sechub-cli.test.ts
- github-actions/scan/src/github-input.ts
- github-actions/scan/src/sechub-cli.ts
> add 'addScmHistory' flag to GitHub actions scan command #3146

- MAINTAINERS.md
> add hamidonos to MAINTAINERS.md and reformat file #3191

- github-actions/scan/README.adoc
> update README.adoc with add-scm-history flag #3146

- github-actions/scan/dist/index.js
> update gh action index.js #3146

- .github/workflows/release-github-action.yml
- github-actions/scan/README.adoc
- github-actions/scan/action.yml
- github-actions/scan/package-lock.json
- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
also
- updated action.yml
- updated package-lock.json (npm ci)
- updated release action order
- updated client configuration overview
---
- closes #3216
> docs updated #3216

- sechub-doc/src/docs/asciidoc/documents/pds/pds_config.adoc
- sechub-doc/src/docs/asciidoc/documents/pds/product_delegation_server_config_example1.json
- sechub-integrationtest/src/main/resources/pds-config-integrationtest.json
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario16/PDSUseSecHubCentralMappingInJobScenario16IntTest.java
- sechub-pds-commons-core/src/main/java/com/mercedesbenz/sechub/pds/commons/core/config/PDSProductSetup.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/config/PDSSummaryLogService.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionCallable.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentService.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSScriptEnvironmentCleaner.java
- sechub-pds/src/main/resources/application-pds_integrationtest.yml
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentServiceTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSScriptEnvironmentCleanerTest.java
This PR
- closes #3220
- closes #3222
> Replace PDS_SCRIPT_ENV_WHITELIST env entry by PDS config entry 

- sechub-pds-solutions/checkmarx/docker/pds-config.json
- sechub-pds-solutions/findsecuritybugs/docker/pds-config.json
- sechub-pds-solutions/gitleaks/docker/pds-config.json
- sechub-pds-solutions/gosec/docker/pds-config.json
- sechub-pds-solutions/iac/docker/pds-config.json
- sechub-pds-solutions/loc/docker/pds-config.json
- sechub-pds-solutions/multi/docker/pds-config.json
- sechub-pds-solutions/owaspzap/docker/pds-config.json
- sechub-pds-solutions/pds-base/docker/pds-config.json
- sechub-pds-solutions/phan/docker/pds-config.json
- sechub-pds-solutions/pmd/docker/pds-config.json
- sechub-pds-solutions/prepare/docker/pds-config.json
- sechub-pds-solutions/scancode/docker/pds-config.json
- sechub-pds-solutions/tern/docker/pds-config.json
- sechub-pds-solutions/xray/docker/pds-config.json
> Added necessary environment whitelist entries for pds-solutions #3226

- sechub-commons-core/src/main/java/com/mercedesbenz/sechub/commons/core/environment/SecureEnvironmentVariableKeyValueRegistry.java
- sechub-commons-core/src/test/java/com/mercedesbenz/sechub/commons/core/environment/SecureEnvironmentVariableKeyValueRegistryTest.java
- sechub-commons-core/src/test/java/com/mercedesbenz/sechub/commons/core/security/CryptoAccessTest.java
- sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/AsciidocGenerator.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/PDSStartupAssertEnvironmentVariablesUsed.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/security/PDSSecurityConfiguration.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSSharedVolumePropertiesSetup.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/PDSStartupAssertEnvironmentVariablesUsedTest.java
> Fix PDS startup problems #3246

- sechub-commons-archive/src/main/java/com/mercedesbenz/sechub/commons/archive/ArchiveTransformationDataFactory.java
- sechub-commons-archive/src/test/java/com/mercedesbenz/sechub/commons/archive/ArchiveTransformationDataFactoryTest.java
> Feature 3243 fix extraction name problem

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSDefaulScriptEnvironmentVariableWhitelist.java
> Added LOGGING_TYPE to default script environment whitelist #3252

- sechub-pds-solutions/prepare/docker/mocks/prepare-mock-status-ok.txt
- sechub-pds-solutions/prepare/docker/scripts/prepare_mock.sh
> Add PDS prepare mock #3297

- sechub-pds-solutions/prepare/docker/Prepare-Debian.dockerfile
> Fixed incorrect naming of wrapper

- build.gradle
- gradle/build-versioning.gradle
- gradle/projects.gradle
- sechub-openapi-java-client/build.gradle
- sechub-openapi-java/build.gradle
- settings.gradle
- Create client and models from sechub-openapi-java in sechub-openapi-java-client
- Remove gradle build stage and add remaining gradle submodules to project build
- Fix error in build-versioning.gradle where file path was not resolved correctly
- Closes #3281
> Generate client and models from sechub-openapi-java #3281

- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/tarbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/tarbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/zipbuilder_test.go
- sechub-cli/src/mercedes-benz.com/sechub/testutil/asserts.go
> cleanup empty files when remote-data-section #3307

- sechub-schedule/src/main/java/com/mercedesbenz/sechub/domain/schedule/encryption/SecHubOutdatedEncryptionPoolSupport.java
> Changed default time for accepted outdated encryption pool entry #3342

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/encryption/PDSEncryptionConfiguration.java
- sechub-pds/src/main/resources/application-pds_integrationtest.yml
- sechub-pds/src/test/resources/application-pds_test.yml
> Removed PDS default encryption setup #3351

- sechub-developertools/scripts/sechub-api.sh
> encryption status api call added #3354

- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_falsepositive_handling.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/false-positives/false-positives-REST-API-content-example1.json
- sechub-doc/src/docs/asciidoc/documents/shared/false-positives/false-positives-howto-define-by-api.adoc
This is just a documentation update. :-)
> documentation regarding fp declaration improved #3390

- .github/workflows/github-action-scan.yml
- .github/workflows/gradle.yml
> Gha feature 3357 enable pull request hook in GitHub action workflow

- .github/workflows/github-action-scan.yml
- .github/workflows/gradle.yml
> 3357 add main, master, develop and hotfix to job execution in gradle.yml & github-action-scan.yml

- .github/workflows/github-action-scan.yml
- .github/workflows/gradle.yml
> fix if statement in github-action-scan.yml & gradle.yml

- sechub-webui-solution/helm/sechub-webui/Chart.yaml
- sechub-webui-solution/helm/sechub-webui/templates/deployment.yaml
- sechub-webui-solution/helm/sechub-webui/values.yaml
> helm chart extended by env variables #3427

- github-actions/scan/README.adoc
Added section that explains variables and config files better.
> Improved GHA documentation

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/util/filepathmatcher.go
> fixed windows client exclude handling #3447

- CONTRIBUTING.md
Also mentioned creating an issue as precondition
- closes #3358
> removed community branch mention #3358

- sechub-cli/src/mercedes-benz.com/sechub/testutil/fileTestHelpers.go
- sechub-cli/src/mercedes-benz.com/sechub/util/fileHelpers.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar.go
- sechub-cli/src/mercedes-benz.com/sechub/util/tar_test.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip.go
- sechub-cli/src/mercedes-benz.com/sechub/util/zip_test.go
Also replaced some occurences of deprecated ioutil calls.
- closes #3367
> client shall not follow symlinks #3367

- sechub-cli/script/supported-source-extensions.txt
> added support for Pro*C file extensions #3271

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
> warn on -addScmHistory but no secretScan #3392

- sechub-commons-model-testframework/src/main/java/com/mercedesbenz/sechub/commons/model/login/TestWebLoginConfigurationBuilder.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidationError.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidator.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/login/TOTPHashAlgorithm.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/login/WebLoginConfiguration.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/login/WebLoginTOTPConfiguration.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidatorTest.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/login/WebLoginTOTPConfigurationTest.java
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example16_webscan_client_certificate_with_openAPI.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example21_webscan_login_form_with_totp.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example2_webscan_anonymous.json
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example4_webscan_login_clientcertificate.json
- sechub-doc/src/test/java/com/mercedesbenz/sechub/ExampleFile.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/ExampleFilesValidTest.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/SchedulerRestControllerRestDocTest.java
- sechub-openapi-java/src/main/resources/openapi.yaml
> Add totp to sechub webscan login config #3471

- sechub-pds-solutions/gitleaks/README.adoc
- sechub-pds-solutions/gitleaks/docker-compose_gitleaks.yaml
- sechub-pds-solutions/gitleaks/docker-compose_pds_gitleaks_external-network.yaml
- sechub-pds-solutions/gitleaks/docker/scripts/gitleaks.sh
- sechub-pds-solutions/gitleaks/env
> Update pds-gitleaks and gitleaks version #3487

- github-actions/scan/action.yml
> Gha feature fix index js root path #3483

- sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_templates_and_assets.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example22_webscan_with_template.json
> Created initial concept for templates and assets #3518

- .github/workflows/release-client-server-pds.yml
- .github/workflows/release-webui.yml
- sechub-developertools/scripts/container/postgres/Dockerfile
- sechub-pds-solutions/tern/tests/alpine/Alpine.dockerfile
- sechub-solution/10-create-image-alpine.sh
- sechub-solution/docker-compose_sechub-alpine.yaml
- sechub-solution/docker/run.sh
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- also updated Alpine version
- and fixed a typo
- closes #3470
> implemented signal handling for sechub server container #3470

- sechub-pds-solutions/iac/env
> Update KICS version in iac-pds

- sechub-web-server-solution/helm/sechub-web-server/templates/deployment.yaml
- sechub-web-server-solution/helm/sechub-web-server/values.yaml
> Renamed value web-server to web_server #3554

- sechub-web-server-solution/docker/copy/README.adoc
> Added copy folder and README.adoc to web-server-solution

- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
> improved getReport client documentation #3578

- sechub-web-ui-solution/10-create-image.sh
- sechub-web-ui-solution/docker/Web-UI-Debian.dockerfile
> web-ui container build with download implemented #3594

- sechub-web-ui-solution/docker/Web-UI-Debian.dockerfile
- sechub-web-ui-solution/docker/run.sh
- sechub-web-ui-solution/helm/web-ui/Chart.yaml
- sechub-web-ui-solution/helm/web-ui/README.md
- sechub-web-ui-solution/helm/web-ui/templates/deployment.yaml
- sechub-web-ui-solution/helm/web-ui/values.yaml
> Feature 3596 web UI ssl keystore

- sechub-pds-solutions/pds-base/docker/PDS-Debian.dockerfile
- sechub-web-server-solution/docker/Web-Server-Debian.dockerfile
- sechub-web-ui-solution/docker/Web-UI-Debian.dockerfile
> enhanced container images #3600

- .github/workflows/release-web-ui.yml
> fixed web-ui release workflow #3620

- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/Chart.yaml
- sechub-pds-solutions/checkmarx/helm/pds-checkmarx/templates/deployment.yaml
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/Chart.yaml
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/templates/deployment.yaml
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/Chart.yaml
- sechub-pds-solutions/gitleaks/helm/pds-gitleaks/templates/deployment.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/Chart.yaml
- sechub-pds-solutions/gosec/helm/pds-gosec/templates/deployment.yaml
- sechub-pds-solutions/iac/helm/pds-iac/Chart.yaml
- sechub-pds-solutions/iac/helm/pds-iac/templates/deployment.yaml
- sechub-pds-solutions/loc/helm/pds-loc/Chart.yaml
- sechub-pds-solutions/loc/helm/pds-loc/templates/deployment.yaml
- sechub-pds-solutions/multi/helm/pds-multi/Chart.yaml
- sechub-pds-solutions/multi/helm/pds-multi/templates/deployment.yaml
- sechub-pds-solutions/owaspzap/helm/pds-owaspzap/Chart.yaml
- sechub-pds-solutions/owaspzap/helm/pds-owaspzap/templates/deployment.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/Chart.yaml
- sechub-pds-solutions/pmd/helm/pds-pmd/templates/deployment.yaml
- sechub-pds-solutions/prepare/helm/pds-prepare/Chart.yaml
- sechub-pds-solutions/prepare/helm/pds-prepare/templates/deployment.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/Chart.yaml
- sechub-pds-solutions/scancode/helm/pds-scancode/templates/deployment.yaml
- sechub-pds-solutions/xray/helm/pds-xray/Chart.yaml
- sechub-pds-solutions/xray/helm/pds-xray/templates/deployment.yaml
- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- readiness check added
- use Spring's readiness probe
- probe timings improved
- closes #3514
> readiness checks added #3514

- sechub-doc/src/docs/asciidoc/sechub-getting-started.adoc
- sechub-website/README.md
- sechub-website/components/Footer.vue
- sechub-website/components/Header.vue
- sechub-website/components/home/Download.vue
- sechub-website/components/home/Features.vue
- sechub-website/components/home/Hero.vue
- sechub-website/nuxt.config.ts
- sechub-website/package-lock.json
- updated website content
- added impressum link
- re-ordered documentation menu
- added docs for IDE plugin to getting-started guide
- cleaned up README.md file
- closes #3001
> Feature 3001 content update sechub website #3001

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/internal/scan/ClientApiWrapper.java
> Fix log message #3725

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/values.yaml
> added Oauth2 section to server Helm Chart #3727

- sechub-pds-solutions/owaspzap/env
> updated wrapper version to 1.7.0 #3729

- sechub-pds-solutions/multi/docker/packages.txt
> updated mobsfscan and njsscan versions #3742

- sechub-web-ui/src/components.d.ts
- sechub-web-ui/src/components/Project.vue
- sechub-web-ui/src/components/ProjectDetails.vue
- sechub-web-ui/src/components/ProjectDetailsFab.vue
- sechub-web-ui/src/components/ProjectsList.vue
- sechub-web-ui/src/i18n/locales/en.json
- sechub-web-ui/src/stores/projectStore.ts
- closes #1896 
- closes #1897
> Added project details to project and jobs overview

- sechub-developertools/scripts/sechub-api.sh
- asset api calls added
- template api calls added
- misc improvements:
- print HTTP return codes instead of nothing
- tar and binary upload simplified and fixed
- check mandatory executables are installed
- code cleanup:
- lowercase local variables
- usage output improved
- 2 blank lines between function declarations
- closes #3765
> added support for assets and templates #3765

- sechub-developertools/scripts/sechub-api.sh
> added server encryption roation call #3773

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/values.yaml
> added security section to Helm chart #3779

- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/ComboxSelectionDialogUI.java
> Changed ordering of cancel and ok button at DAUI #3781

- sechub-solution/helm/sechub-server/templates/networkpolicy.yaml
- sechub-web-ui-solution/docker/nginx/nginx.conf
> server access from web-ui enabled #3786

- sechub-pds-solutions/owaspzap/docker/scripts/owasp-zap.sh
> Explicitly set geckodriver system property #3800

- sechub-doc/src/docs/asciidoc/documents/architecture/about-arc42.adoc
> Changed broken link in arc42 about doc #3807

- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/project/ProjectRepositoryCustom.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/project/ProjectRepositoryImpl.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/project/ProjectTemplateService.java
- sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/scheduler/SchedulerAdministrationMessageHandler.java
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/ProjectRepositoryDBTest.java
- sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/project/ProjectTemplateServiceTest.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario1/TemplateScenario1IntTest.java
- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/template/TemplateService.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/template/TemplateServiceTest.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/MessageID.java
> Implemented template delete handling in admin domain #3848

- sechub-pds-solutions/owaspzap/README.adoc
- sechub-pds-solutions/owaspzap/docker/scripts/owasp-zap.sh
- sechub-wrapper-owasp-zap/README.adoc
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/cli/CommandLineSettings.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContext.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapScriptLoginWebDriverFactory.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapWrapperGroovyScriptExecutor.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/util/EnvironmentVariableConstants.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactoryTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapWrapperGroovyScriptExecutorTest.java
- sechub-wrapper-owasp-zap/src/test/resources/example-pac-files/test-proxy.pac
- closes #3834 
- closes #3847
> Support PAC file in wrapper and pds solution #3834

- sechub-pds-solutions/owaspzap/env
> updated zap wrapper version #3861

- github-actions/scan/README.adoc
- github-actions/scan/__test__/integrationtest.test.ts
- github-actions/scan/__test__/integrationtest/03-init_sechub_data.sh
- github-actions/scan/__test__/integrationtest/test-config/executor-codescan-red-def-fp.json
- github-actions/scan/__test__/integrationtest/test-config/gha_integrationtest_pds-config.json
- github-actions/scan/__test__/integrationtest/test-product-output/example-codescan-sarif-output-red.json
- github-actions/scan/__test__/integrationtest/test-scripts/pds-codescan-demo-red-define-false-positives.sh
- github-actions/scan/__test__/sechub-cli.test.ts
- github-actions/scan/action.yml
- github-actions/scan/dist/index.js
- github-actions/scan/package-lock.json
- github-actions/scan/package.json
- github-actions/scan/src/github-input.ts
- github-actions/scan/src/launcher.ts
- github-actions/scan/src/sechub-cli.ts
> Add defineFalsePositives step to GH action before scan execution #2078

- sechub-commons-security-spring/src/main/resources/templates/login.html
> Feature 3585 request new api token on login form

- sechub-web-ui-solution/docker/nginx/nginx.conf
> Web-UI: NGINX shall not reveal its version #3898

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/communication/CommunicationDataConversionType.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/communication/CommunicationDataConverter.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/communication/CommunicationDataConverterConfig.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/communication/CommunicationDataConverterConfigTest.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/communication/CommunicationDataConverterTest.java
- sechub-commons-model/src/test/resources/communciation/communication-key-converter-config1.json
> Introduce communcation data converter #3712

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/deployment.yaml
- sechub-solution/helm/sechub-server/values.yaml
> added classic auth cookie timeout #3850

- sechub-commons-core/src/main/java/com/mercedesbenz/sechub/commons/core/util/SimpleStringUtils.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/AbstractSecurityConfiguration.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/LoginEnabledCondition.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/LoginModeOAuth2ActiveCondition.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/SecHubSecurityProperties.java
- sechub-commons-security-spring/src/test/java/com/mercedesbenz/sechub/spring/security/LoginModeOAuth2ActiveConditionTest.java
- sechub-commons-security-spring/src/test/java/com/mercedesbenz/sechub/spring/security/SecHubSecurityPropertiesTest.java
- sechub-commons-security-spring/src/test/resources/application-jwt-test.yml
- sechub-commons-security-spring/src/test/resources/application-login-mode-oauth2-active-condition-test.yaml
- sechub-commons-security-spring/src/test/resources/application-opaque-token-test.yml
- sechub-commons-security-spring/src/test/resources/application-security-properties-test.yaml
- sechub-doc/src/docs/asciidoc/documents/shared/launchconfig/launchconfig_start_dev_server.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/springboot_security.adoc
- sechub-doc/src/docs/asciidoc/documents/techdoc/02_security_in_development.adoc
- sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/AsciidocGenerator.java
- sechub-server/src/main/resources/application-localserver.yml
- sechub-server/src/test/resources/application-test.yml
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SecHubApplicationContextCloseHandler.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SecHubApplicationFailedHandler.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SpringApplicationShutdownHandler.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SecHubApplicationContextCloseHandlerTest.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SecHubApplicationFailedHandlerTest.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SpringApplicationShutdownHandlerTest.java
> Handle SecHub Server 2.6.0 startup and documentation problems #3917

- .github/workflows/sechub-plugin-vscode-release.yml
- sechub-web-ui-solution/docker/nginx/nginx.conf
- sechub-web-ui-solution/docker/nginx/sechub_login_check.conf
- closes #3934 
- closes #3935
> Web-UI: New redirect for /login #3935

- sechub-web-ui-solution/docker/nginx/nginx.conf
> avoid HTTP 404 for deep links #3942

- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/JSONConverter.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/JSONValidatable.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/JSONValidationException.java
Closes https://github.com/mercedes-benz/sechub/issues/3885
@lorriborri - Had to create a new PR since the branch name needed changing—closed the previous one (https://github.com/mercedes-benz/sechub/pull/3890).
> Auto validate jsonconverter objects

- LICENSE
- ide-plugins/vscode/LICENSE
- sechub-doc/src/docs/asciidoc/documents/shared/about_sechub.adoc
- sechub-pds-solutions/README.adoc
- sechub-pds-solutions/findsecuritybugs/helm/pds-findsecuritybugs/LICENSE
- sechub-pds-solutions/gosec/helm/pds-gosec/LICENSE
- sechub-pds-solutions/multi/helm/pds-multi/LICENSE
- sechub-pds-solutions/pmd/helm/pds-pmd/LICENSE
- sechub-pds-solutions/scancode/helm/pds-scancode/LICENSE
- closes #3949 
- closes #3950
> documentation updated #3950

- sechub-commons-model-testframework/src/main/java/com/mercedesbenz/sechub/commons/model/login/TestWebLoginConfigurationBuilder.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidationError.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidator.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/login/WebLoginConfiguration.java
- sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/login/WebLoginVerificationConfiguration.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidatorTest.java
- sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/login/WebLoginVerificationConfigurationTest.java
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc
- sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example24_webscan_login_form_with_verification.json
- sechub-doc/src/test/java/com/mercedesbenz/sechub/ExampleFilesValidTest.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/TestSecHubConfigExampleFile.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/SchedulerRestControllerRestDocTest.java
- sechub-openapi-java/src/main/resources/openapi.yaml
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/cli/ZapWrapperExitCode.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContext.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/internal/scan/ClientApiWrapper.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
> Extended sechub webscan configuration model with verification

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/util/Counter.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/CounterTest.java
> Count amount of logins during scans

- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/help.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/signalhandler.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/urlbuilder_test.go
- job cancelling action inplemented
- signal handling implemented for SIGINT and SIGTERM signals
- closes #3965
> Feature 3965 client add cancel functionality

- CONTRIBUTING.md
- MAINTAINERS.md
- SECURITY.md
- ide-plugins/eclipse/README.md
- ide-plugins/jetbrains/README.md
- ide-plugins/vscode/README.md
- sechub-cli/src/mercedes-benz.com/sechub/cli/testdata/README.md
- sechub-integrationtest/src/test/resources/checksum-testfiles/README.md
- sechub-pds/src/main/resources/certificates-untracked/README.md
- sechub-server/src/main/resources/certificates-untracked/README.md
What changes were proposed in this pull request?
This PR fixes a large number of Markdown lint issues across multiple .md files in the repository. The issues were identified using markdownlint, and approximately 90-95% of them have been resolved.
Why are the changes needed?
Improves Markdown formatting consistency.
Enhances readability and maintainability of documentation.
Reduces unnecessary lint warnings/errors for better developer experience.
fixes #3955 
Does this PR introduce any user-facing change?
No, these are documentation improvements and do not affect functionality.
> Improve documentation formatting and clarity in multiple README files

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/networkpolicy.yaml
- sechub-solution/helm/sechub-server/values.yaml
> switch added for enabling internal access #4025

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapWrapperGroovyScriptExecutor.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapWrapperGroovyScriptExecutorTest.java
- closes #4023 
- closes #4038 4038
> Add error handling to retrieveBrowserStorage #4023

- sechub-solution/helm/sechub-server/Chart.yaml
- sechub-solution/helm/sechub-server/templates/networkpolicy.yaml
- sechub-solution/helm/sechub-server/values.yaml
- sechub-web-ui-solution/helm/web-ui/Chart.yaml
- sechub-web-ui-solution/helm/web-ui/templates/deployment.yaml
> server access only with role sechub-frontend #4043

- sechub-pds-solutions/owaspzap/env
Updated the OWASP_ZAP_WRAPPER_VERSION
> 2 - After release: Merge master back into develop

- sechub-web-ui-solution/README.adoc
- sechub-web-ui/.gitignore
- sechub-web-ui/README.md
- sechub-web-ui/src/components/ProjectJobList.vue
- sechub-web-ui/src/components/UserDetailInformation.vue
- sechub-web-ui/src/config.ts
- sechub-web-ui/src/types/global.d.ts
- closes #3888
- mini bug fix for pagination
> Added support email and website as configurable  ENV 

- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig_test.go
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/WithSecHubClient.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/SecHubClientExecutor.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario21/PDSSolutionMockModeScenario21IntTest.java
- sechub-integrationtest/src/test/resources/solution-mocks/code-testproject/src/hello_world.go
- sechub-integrationtest/src/test/resources/solution-mocks/iac-testproject/deploy/outputs.tf
- sechub-integrationtest/src/test/resources/solution-mocks/web-testproject/openapi.json
> Support Iac scan type by client 

- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/DynamicBearerTokenResolver.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/LoginClassicSuccessHandler.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/monitoring/PDSHeartBeatTriggerService.java
This PR
- closes #4079 
- closes #2968
> Feature 4079 reduce massive log entries

- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/controller_test.go
> Client: verify config for forbidden names #3897

- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertProject.java
> Changed ordering of expected and values #4094

- sechub-commons-core/src/main/java/com/mercedesbenz/sechub/commons/core/cache/InMemoryCache.java
- sechub-commons-core/src/test/java/com/mercedesbenz/sechub/commons/core/cache/InMemoryCacheTest.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/AES256EncryptionException.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/AbstractSecurityConfiguration.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenExpirationCalculator.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenIntrospectionResponse.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenIntrospector.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/PortAccessGuard.java
- sechub-commons-security-spring/src/test/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenExpirationCalculatorTest.java
- sechub-commons-security-spring/src/test/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenIntegrationTest.java
- sechub-commons-security-spring/src/test/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenIntrospectorTest.java
> Expired opaque tokens do now lead to 401 which removes cookie #3892

- github-actions/scan/__test__/sechub-cli.test.ts
- github-actions/scan/dist/index.js
- github-actions/scan/src/sechub-cli.ts
> Pass all environment variables to the sechub client call #4096

- sechub-server/src/main/resources/application-integrationtest.yml
- sechub-server/src/main/resources/application.yml
- sechub-solution/docker-compose_sechub-debian-prepare.yaml
- sechub-solution/docker-compose_sechub-debian.yaml
- sechub-solution/docker-compose_sechub-fedora.yaml
- sechub-solution/docker-compose_sechub-rocky.yaml
- sechub-solution/docker-compose_sechub-ubuntu.yaml
- sechub-solution/docker-compose_sechub_cluster.yaml
- sechub-solution/env-sechub
- sechub-solution/helm/sechub-server/values.yaml
> Added security encryption key by default 

- .github/workflows/github-action-scan.yml
- github-actions/scan/README.adoc
- github-actions/scan/__test__/client-version-helper.test.ts
- github-actions/scan/__test__/integrationtest.test.ts
- github-actions/scan/__test__/post-scan.test.ts
- github-actions/scan/__test__/sechub-cli.test.ts
- github-actions/scan/action.yml
- github-actions/scan/dist/index.js
- github-actions/scan/package-lock.json
- github-actions/scan/package.json
- github-actions/scan/src/client-download.ts
- github-actions/scan/src/client-version-helper.ts
- github-actions/scan/src/fs-helper.ts
- github-actions/scan/src/fs-wrapper.ts
- github-actions/scan/src/github-input.ts
- github-actions/scan/src/init-scan.ts
- github-actions/scan/src/launcher.ts
- github-actions/scan/src/platform-helper.ts
- github-actions/scan/src/post-scan.ts
- github-actions/scan/src/projectname-resolver.ts
- github-actions/scan/src/sechub-cli.ts
- github-actions/scan/tsconfig.json
> Feature 4103 provide build as go client version to use

- github-actions/scan/README.adoc
- github-actions/scan/__test__/input-helper.test.ts
- github-actions/scan/dist/index.js
- github-actions/scan/src/fs-helper.ts
- github-actions/scan/src/input-helper.ts
> Add proxy to client download using http(s)_proxy #4060

- github-actions/scan/dist/index.js
- github-actions/scan/src/environment.ts
- sechub-cli/src/mercedes-benz.com/sechub/cli/config.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context-initializer.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/context-initializer_test.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job_test.go
- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/IntegrationTestSupport.java
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/WithSecHubClient.java
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/TestUtil.java
> Feature 4128 client enable zero returncode on red

- sechub-server/src/main/resources/application-integrationtest.yml
- sechub-server/src/main/resources/application.yml
- sechub-solution/docker/run.sh
- sechub-solution/env-sechub
> Added default AES-key generation

- sechub-cli/src/mercedes-benz.com/sechub/cli/controller.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/job.go
- sechub-cli/src/mercedes-benz.com/sechub/cli/signalhandler.go
- sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc
> cancel action extended and documented #3978

- sechub-pds-solutions/findsecuritybugs/01-start-single-docker-compose.sh
- sechub-pds-solutions/findsecuritybugs/05-start-single-sechub-network-docker-compose.sh
> Added copy install-java to findsecuritybugs start script 

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContext.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/internal/scan/ClientApiWrapper.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java
- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapScriptLogin.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
- sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/login/ZapScriptLoginTest.java
> Improve product user messages #4139

- sechub-adapter-checkmarx/src/main/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxResilienceConsultant.java
- sechub-adapter-checkmarx/src/test/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxAdapterV1WireMockTest.java
- sechub-adapter-checkmarx/src/test/java/com/mercedesbenz/sechub/adapter/checkmarx/CheckmarxResilienceConsultantTest.java
- sechub-wrapper-checkmarx/src/test/java/com/mercedesbenz/sechub/wrapper/checkmarx/scan/CheckmarxWrapperScanServiceTest.java
> Feature 4169 fix bug in CheckmarxResilienceConsultant

- sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_templates_and_assets.adoc
- sechub-pds-solutions/owaspzap/README.adoc
- sechub-pds-solutions/owaspzap/docker/scripts/owasp-zap.sh
> rename script.groovy to login-script.groovy

- sechub-pds-solutions/.gitignore
- sechub-pds-solutions/pds-base/10-create-image.sh
- sechub-pds-solutions/pds-base/docker/PDS-Debian.dockerfile
> add pds-api.sh to pds-base image #4180

- sechub-integrationtest/integrationtest-pds.sh
- sechub-integrationtest/integrationtest-server.sh
- Set the default Spring Management Port to 20250 (SecHub server) and 20251 (PDS)
- Check if the spawned process has ended when waiting to get ready
- improved shellscript code
- closes #4183
> integrationtest scripts improved #4183

- github-actions/scan/README.adoc
- github-actions/scan/dist/index.js
- github-actions/scan/package-lock.json
- github-actions/scan/package.json
- github-actions/scan/src/input-helper.ts
> Feature 4171 Github Action info log when proxy is configured and used

- .github/workflows/release-web-ui.yml
- sechub-web-ui-solution/docker/Web-UI-Debian.dockerfile
- sechub-website/build-sechub-website.sh
> Use `npm ci` instead `npm install` for all automated builds #4193

- sechub-website/README.md
- sechub-website/assets/css/tailwind.css
- sechub-website/components/home/Download.vue
- sechub-website/nuxt.config.ts
- sechub-website/package-lock.json
- sechub-website/package.json
- sechub-website/tailwind.config.js
- closes #3744 
- closes #3889
Tested with docker-compose setup on https://localhost 
Part of the solution can be found [here](https://masteringnuxt.com/blog/integrating-headlessui-and-tailwindcss-with-nuxtjs-a-comprehensive-guide)
> Fixed website by using correct dependencies #3744

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentService.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSKeyToEnvConverter.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSSafeProcessEnvironmentAccess.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSKeyToEnvConverterTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/execution/PDSSafeProcessEnvironmentAccessTest.java
> Introduce PDSSafeProcessEnvironmentAccess #4209

- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/clustercache/OAuth2OpaqueTokenClusterCache.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/clustercache/OAuth2OpaqueTokenClusterCachePersistence.java
- sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/security/clustercache/OAuth2OpaqueTokenClusterCachePersistenceTest.java
> Handle opaque token database cache updates correctly #4220

- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/clustercache/OAuth2OpaqueTokenClusterCachePersistence.java
> Added success logging on retry #4243

- sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/config/ZapScanContextFactory.java
> Add product message on invalid template configuration #4223

- sechub-website/README.md
- sechub-website/components/Header.vue
- sechub-website/nuxt.config.ts
> Fature 4248 foss website bug fix

- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/AbstractSecurityConfiguration.java
- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/StatelessAuthorizationRequestRepository.java
- sechub-commons-security-spring/src/main/resources/templates/login.html
- sechub-commons-security-spring/src/test/java/com/mercedesbenz/sechub/spring/security/StatelessAuthorizationRequestRepositoryTest.java
- sechub-server/src/main/resources/application.yml
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/APIConstants.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/SecHubSecurityConfiguration.java
> Feature 4245 make oauth2 login workflow stateless

- sechub-solutions-shared/setup-with-kubernetes/include.sh
> fixed lb detection #4298

- github-actions/scan/README.adoc
- github-actions/scan/__test__/configuration-builder.test.ts
- github-actions/scan/__test__/configuration-model.test.ts
- github-actions/scan/__test__/integrationtest.test.ts
- github-actions/scan/__test__/integrationtest/03-init_sechub_data.sh
- github-actions/scan/__test__/integrationtest/test-config/executor-iacscan-red.json
- github-actions/scan/__test__/integrationtest/test-config/gha_integrationtest_pds-config.json
- github-actions/scan/__test__/integrationtest/test-config/sechub-config-iacscan-test-project-8.json
- github-actions/scan/__test__/integrationtest/test-product-output/example-iacscan-sarif-output-red.json
- github-actions/scan/__test__/integrationtest/test-scripts/pds-iacscan-demo-red.sh
- github-actions/scan/action.yml
- github-actions/scan/dist/index.js
- github-actions/scan/src/configuration-builder.ts
- github-actions/scan/src/configuration-model.ts
- sechub-developertools/scripts/sdc.sh
> add iacscan model #4055

- sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/report/DownloadScanReportService.java
- sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/report/DownloadScanReportServiceTest.java
> Fixed job report handling logic #4346

- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/config/PDSHardExitSupport.java
- sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/config/PDSServerConfigurationService.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/config/PDSServerConfigurationServiceTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/job/PDSJobRepositoryDBTest.java
- sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/monitoring/PDSPDSHeartBeatRepositoryDBTest.java
> Do hard PDS exit when no server configuration #4302

- gradle/projects.gradle
- sechub-assistant/build.gradle
- sechub-assistant/src/main/java/com/mercedesbenz/sechub/assistant/AssistantRestController.java
- sechub-assistant/src/main/java/com/mercedesbenz/sechub/assistant/FindingAssistantService.java
- sechub-developertools/build.gradle
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/DeveloperAdministration.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java
- sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/action/assistant/AskAssistantAction.java
- sechub-doc/src/docs/asciidoc/diagrams/diagram_concept_sechub_assistant-model.puml
- sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_assistant.adoc
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/AssistantRestControllerRestDocTest.java
- sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/TestOpenApiSchema.java
- sechub-integrationtest/build.gradle
- sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsUser.java
- sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario9/PDSCodeScanSarifJobScenario9IntTest.java
- sechub-openapi/src/main/resources/openapi.yaml
- sechub-server-core/build.gradle
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/assistant/UseCaseUserRequestFindingExplanation.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/assistant/UseCaseUserRequestsFindingExplanation.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/APIConstants.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/SecHubSecurityConfiguration.java
- sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/UseCaseIdentifier.java
- sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/SecHubTestURLBuilder.java
- settings.gradle
> Feature 3708 provide explanation rest api

- sechub-pds-solutions/gosec/env
> upgrade to latest gosec release #4356

- github-actions/scan/package.json
> Update version according to the milestone #4378

- continous-integration-multibranch-pipeline.jenkins
> jenkins build is fixed #4380

- sechub-commons-security-spring/src/main/java/com/mercedesbenz/sechub/spring/security/OAuth2OpaqueTokenIntrospector.java
> #4401 extend debug logs in OAuth2OpaqueTokenIntrospector
