sechub-scan-testframework/src/main/java/com/daimler/sechub/domain/scan/AssertSecHubResult.java
* referencing values.hostnames instead of variable method argument hostnames that should be identical to hostNameAsList
* finding based on [lgtm scan results](https://lgtm.com/projects/g/Daimler/sechub/snapshot/91c873adb7b33b1313458e3971ff157c16557bb2/files/sechub-scan-testframework/src/main/java/com/daimler/sechub/domain/scan/AssertSecHubResult.java?sort=name&dir=ASC&mode=heatmap#x89fd7db2580d923f:1)
=> Fixed failed assertion message

sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/scenario2/FileUploadSizeScenario2IntTest.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/SchedulerUploadService.java, sechub-server/src/main/java/com/daimler/sechub/server/SecHubExceptionHandler.java, sechub-server/src/main/java/com/daimler/sechub/server/SecHubTomcatServletWebserFactory.java
- problem was that tomcat has got a "maxswallow" configuration
which sometimes did the connection resets and sometimes normal
spring behaviour did throw an internal server error
- added special setup for tomcat maxswallow: Is now always 1 MB more
than the configured spring max uploax file size
- upload exceptions now handled by SecHubExceptionHandler and switched
to response status NOT_ACCEPTABLE
- test does now check too bigfiles return now NOT_ACCEPTABLE
- changed some minor parts inside test as well
=> Fixed flaky test + changed server behaviour, closes #160

sechub-cli/src/daimler.com/sechub/cli/config.go, sechub-cli/src/daimler.com/sechub/cli/constants.go, sechub-cli/src/daimler.com/sechub/cli/controller.go, sechub-cli/src/daimler.com/sechub/util/filepathmatcher.go, sechub-cli/src/daimler.com/sechub/util/filepathmatcher_test.go, sechub-cli/src/daimler.com/sechub/util/zip.go, sechub-doc/src/docs/asciidoc/documents/shared/configuration/scan_config.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example1_sourcescan_filesystem.json
- implemented default exclude directory patterns
- fixed documentation's json example code (bracket was missing), example for directories, because files will be covered with #256
- re-implementation of func Filepathmatch via regexp matching which is more simple and also fixes #260
- added tests for above
closes #227 
closes #260 
---
=> Client: implementation of default exclude patterns #227 #260

sechub-adapter-checkmarx/src/main/java/com/daimler/sechub/adapter/checkmarx/CheckmarxAdapterConfig.java, sechub-adapter-checkmarx/src/main/java/com/daimler/sechub/adapter/checkmarx/CheckmarxConfig.java, sechub-adapter-checkmarx/src/main/java/com/daimler/sechub/adapter/checkmarx/MockedCheckmarxAdapter.java, sechub-adapter-checkmarx/src/main/java/com/daimler/sechub/adapter/checkmarx/support/CheckmarxOAuthSupport.java, sechub-adapter-checkmarx/src/test/java/com/daimler/sechub/adapter/checkmarx/CheckmarxAdapterV1WireMockTest.java, sechub-adapter-checkmarx/src/test/java/com/daimler/sechub/adapter/checkmarx/CheckmarxConfigTest.java, sechub-adapter-nessus/src/main/java/com/daimler/sechub/adapter/nessus/MockedNessusAdapter.java, sechub-adapter-netsparker/src/main/java/com/daimler/sechub/adapter/netsparker/MockedNetsparkerAdapter.java, sechub-adapter-pds/src/main/java/com/daimler/sechub/adapter/pds/MockedPDSAdapter.java, sechub-adapter/src/main/java/com/daimler/sechub/adapter/mock/AbstractMockedAdapter.java, sechub-adapter/src/main/java/com/daimler/sechub/adapter/mock/MockedAdapter.java, sechub-adapter/src/test/java/com/daimler/sechub/adapter/mock/AbstractMockedAdapterTest.java, sechub-scan-product-checkmarx/src/main/java/com/daimler/sechub/domain/scan/product/checkmarx/CheckmarxInstallSetup.java, sechub-scan-product-checkmarx/src/main/java/com/daimler/sechub/domain/scan/product/checkmarx/CheckmarxInstallSetupImpl.java, sechub-scan-product-checkmarx/src/main/java/com/daimler/sechub/domain/scan/product/checkmarx/CheckmarxProductExecutor.java, sechub-scan-product-checkmarx/src/test/java/com/daimler/sechub/domain/scan/product/checkmarx/CheckmarxProductExecutorMockTest.java
- sanity check inside mocks does now work again (was not
executed before this commit, because not using spring boot values
to check if sanity check was enabled)
- added some junit tests for config
- added mock sanity check methdo for checkmarx client secret
---
=> Made checkmarx client secret configurable + fixed some minor bugs #212

sechub-scan-product-sereco/src/main/java/com/daimler/sechub/domain/scan/product/sereco/SerecoReportProductExecutor.java, sechub-scan/src/main/java/com/daimler/sechub/domain/scan/ScanJobExecutor.java, sechub-scan/src/main/java/com/daimler/sechub/domain/scan/ScanService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/SchedulerApproveJobService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/SchedulerCancelJobService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/SchedulerCreateJobService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/SchedulerRestartJobService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/SchedulerUploadService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/batch/ScanExecutionTasklet.java, sechub-server/src/main/java/com/daimler/sechub/server/SecHubServerMDCAsyncHandlerInterceptor.java, sechub-server/src/main/java/com/daimler/sechub/server/SecHubWebMvcConfigurer.java, sechub-server/src/test/java/com/daimler/sechub/server/SecHubServerMDCAsyncHandlerInterceptorTest.java, sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/LogConstants.java
- rest calls do now automatically clear MDC of their thread
- rest calls try to estimate project and job uuid by request URI
and set automatically into MDC
- parts having additonal threads do set and reset by their own
---
=> Changed MDC logging #293

sechub-cli/build.gradle, sechub-cli/src/daimler.com/sechub/testutil/fileTestHelpers.go
- workingDir variable is unused in linterGo (removed from task)
- added testutil package (although only for testing, we should have clean code there, also)
- fix of lint complaint in fileTestHelpers.go
closes #313
=> improvements linterGo gradle task #313

sechub-doc/src/test/java/com/daimler/sechub/restdoc/AnonymousCheckAliveRestDocTest.java, sechub-server-core/src/main/java/com/daimler/sechub/server/core/AnonymousCheckAliveRestController.java
Changes check/alive from HTTP HEAD to GET method for Kubernetes LivenessProbe
--- 
=> #378: changed /check/alive endpoint from HTTP HEAD only to HTTP GET

sechub-doc/src/docs/asciidoc/diagrams/diagram_overview_execution_profiles_and_config.puml, sechub-doc/src/docs/asciidoc/documents/architecture/08_concepts.adoc, sechub-doc/src/docs/asciidoc/documents/operations/01_sechub_server.adoc, sechub-doc/src/docs/asciidoc/documents/operations/02_security_products.adoc, sechub-doc/src/docs/asciidoc/documents/shared/concepts/execution-profiles/concept_execution_profiles_and_config.adoc, sechub-doc/src/docs/asciidoc/documents/shared/concepts/false-positive-handling/false-positive-handling.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/initial_profile_and_executor_config.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/mapping.adoc, sechub-doc/src/docs/asciidoc/sechub-operations.adoc, sechub-doc/src/main/java/com/daimler/sechub/docgen/usecase/UseCaseAsciiDocGenerator.java, sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/usecases/UseCaseIdentifier.java, sechub-shared-kernel/src/test/java/com/daimler/sechub/sharedkernel/usecases/UseCaseIdentifierTest.java
- added documentation for execution profiles and executor configuration
- changed UsecaseIdentifier enumeration: developers now MUST define
id inside constructor. Reason: So it's clear which number is used
inside documentation. Uniqueness and avoiding of fragmentation is
solved by unit tests
---
=> Added documentation + made usecase numbers defined in code , closes #406

sechub-test/src/test/java/com/daimler/sechub/test/RoutesTest.java
closes #496
Big chunks of "changed code" occur because of automatic reformatting. The actual fix is replacing of "computeIfAbsent" usage.
---
=> #496: fixed concurrency modification exception for newer Java versions

libraries.gradle
- upgrade commons-validator to v1.7
- commons-validator upgrades Apache commons beanutils to 1.9.4 -> fixes CVE-2019-10086
Closes: #642
=> Feature 642 upgrade beanutils

build, buildDoc, sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
- added sechub client example
- added create project
- jdk8 -> jdk11
- made more release-agnostic
(otherwise we would have to update the docs for
every Debian/CentOS/Fedora/Alpine/Ubuntu release)
- created a build shell script for easy build
- updated buildDocs script to use above
closes #305
=> improve-quickstart-guide #305

gradle/wrapper/gradle-wrapper.properties, sechub-pds/src/main/java/com/daimler/sechub/pds/PDSSystemPropertyInjector.java, sechub-pds/src/main/resources/application.yml, sechub-server/src/main/java/com/daimler/sechub/server/SecHubSystemPropertyInjector.java, sechub-server/src/main/resources/application.yml
- introduce SystemPropertyInjector classes and
special keys for PDS and SecHub server, so configurable
by `application.yaml` files
- `application.yaml` files do now contain 2048 as default value
- documentation will be generated and points to issue at github
for details
=> Changed default diffie hellman length to 2048 #689

sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/security/ServerSecurityLogHandlingTest.java
This PR 
- closes #692 
- instead of 8443 the test does now correctly use port information
from TestPortProvider
=> Fix failing Jenkins builds #692

buildDoc, sechub-cli/src/daimler.com/sechub/cli/constants.go, sechub-cli/src/daimler.com/sechub/util/zip_test.go
- added pattern "node_modules" to default exclude list
- added test for the same
closes #593
=> ignore directories named "node_modules"

.github/workflows/create-releases.yml
- add new OpenAPI gradle task names
closes: #740
=> Fix OpenAPI generation in release github action

.github/dependabot.yml, .github/workflows/create-releases.yml, .github/workflows/gradle.yml, build.gradle, sechub-server-core/build.gradle, sechub-storage-s3-aws-test/build.gradle, sechub-storage-s3-aws/build.gradle
The set up of caches reduce build time from 18 to 12 min.
This partially treats #688
I have also included dependabot for github-actions dependencies handling. It can also be activated for gradle if you are interested. 
Several gradle dependencies are also updated.
=> Set up cache for gradle and go 

sechub-pds-examples/gosec/05-start-single-sechub-network-docker-compose.sh, sechub-pds-examples/gosec/70-test.sh, sechub-pds-examples/gosec/README.adoc, sechub-pds-examples/gosec/docker-compose_pds_gosec_alpine-external-network.yaml, sechub-pds-examples/gosec/docker-compose_pds_gosec_ubuntu-external-network.yaml, sechub-pds-examples/gosec/docker/GoSec-Alpine.dockerfile, sechub-pds-examples/gosec/docker/GoSec-Ubuntu.dockerfile, sechub-pds-examples/gosec/docker/gosec.sh, sechub-pds-examples/gosec/docker/gosec_mock.sh, sechub-pds-examples/gosec/docker/mock.sarif.json, sechub-pds-examples/gosec/docker/pds-config.json, sechub-pds-examples/gosec/helm/pds-gosec/Chart.yaml, sechub-pds-examples/gosec/helm/pds-gosec/LICENSE, sechub-pds-examples/gosec/helm/pds-gosec/README.md
Fixes multiple issues:
- Make PDS+GoSec part of the SecHub network #872
- Update PDS to 0.24.0 #870
- Update Go in Ubuntu to 1.7.2 #870
- Update GoSec to 2.9.1 #870
- Download dependencies into download folder #822
- Add AGPL notice for MinIO #821
- Add maintainers, README.md and LICENSE file for Helm chart #779
- Introduces a PDS_GOSEC_MOCK product #871
closes: #872
closes: #871 
closes: #870
closes: #822
closes: #821 
closes: #779
=> AGPL notice and more

sechub-adapter-pds/src/main/java/com/daimler/sechub/adapter/pds/DelegatingMockablePDSAdapterV1.java, sechub-adapter-pds/src/main/java/com/daimler/sechub/adapter/pds/MockedPDSAdapterV1.java, sechub-adapter-pds/src/test/java/com/daimler/sechub/adapter/pds/DelegatingMockablePDSAdapterV1Test.java, sechub-adapter/src/main/java/com/daimler/sechub/adapter/mock/AbstractMockedAdapter.java, sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/internal/IntegrationTestDefaultExecutorConfigurations.java
- integration tests do now use "pds.mocking.disabled"
job parameter with "true"
- only when "pds.mocking.disabled" a real PDS adapter
is used, otherwise mock variant is used when
spring boot profile "mocked_products" is set
- setupService is now set to created mock and
fixes #881
- fixes #869
=> Changed mock handling for PDS #869, #881

build.gradle, libraries.gradle, sechub-analyzer-cli/build.gradle, sechub-client-java/build.gradle, sechub-commons-model/build.gradle, sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/monitoring/MemoryRuntime.java, sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/monitoring/MemoryUsageMonitor.java, sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/monitoring/SystemMonitorService.java, sechub-shared-kernel/src/test/java/com/daimler/sechub/sharedkernel/monitoring/MemoryRuntimeTest.java, sechub-shared-kernel/src/test/java/com/daimler/sechub/sharedkernel/monitoring/MemoryUsagePercentMonitorTest.java, sechub-storage-core/build.gradle, sechub-storage-s3-aws-test/build.gradle, sechub-testframework/build.gradle
- Upgraded SpringBoot to 2.5.7 and 
- Introduced mockito inline to avoid `illegal reflective access operation`. For more information: https://github.com/mockito/mockito/issues/1325.
Closes: #908
=> Upgrade SpringBoot to 2.5.7

sechub-pds-solutions/gosec/01-start-single-docker-compose.sh, sechub-pds-solutions/gosec/05-start-single-sechub-network-docker-compose.sh, sechub-pds-solutions/gosec/10-create-ubuntu-image.sh, sechub-pds-solutions/gosec/50-start-multiple-docker-compose.sh, sechub-pds-solutions/gosec/51-start-multiple-object-storage-docker-compose.sh, sechub-pds-solutions/gosec/70-test.sh, sechub-pds-solutions/gosec/docker/GoSec-Alpine.dockerfile, sechub-pds-solutions/gosec/docker/GoSec-Ubuntu.dockerfile, sechub-pds-solutions/gosec/docker/mock.sarif.json
Upgrade GoSec and refactor docker files
- Upgrade GoSec to 2.9.5
- Add a new mock.sarif.json file generated by GoSec 2.9.5
- Refactor dockerfiles
- Add `wget` command to download checksum for PDS
- Add `--remove-orphans` to build command
- No verbose output of wget
closes: #921
=> Upgrade GoSec + PDS

sechub-pds/src/main/java/com/daimler/sechub/pds/monitoring/PDSAnonymousCheckAliveRestController.java, sechub-pds/src/test/java/com/daimler/sechub/pds/monitoring/PDSAnonymousCheckAliveRestControllerMockTest.java
Extend the check alive call to include GET as a possible method. This is important for readiness and liveliness probes in Kubernetes.
closes: #918
=> introduce check alive via GET

apply-headers.sh, sechub-other/spdx/template/spdx_template_doubleslash.txt, sechub-other/spdx/template/spdx_template_hash.txt, sechub-other/spdx/template/spdx_template_md.txt
- use sed to insert spdx messages
- Bash script support (2nd line inserts)
- Batch, SQL, Ruby, C, Python file support
- safe coloring
- removed are-you-sure because changes can be undone easily via git
- removed template files (redundant contents) in favor of doing it inside the script with one variable
closes #436
=> apply-headers script refactored + bash support

build-java.gradle, build-spring.gradle, build.gradle, libraries.gradle, sechub-administration/build.gradle, sechub-analyzer-cli/build.gradle, sechub-authorization/build.gradle, sechub-sereco/build.gradle, sechub-server/src/main/resources/application.yml, sechub-storage-sharedvolume-spring/build.gradle
- upgrade SpringBoot to 2.6
- upgrade Restdoc
- add Dom4J dependency, because it is not a Hibernate dependency anymore
- rewrite build.gradle of sechub-sereco and
sechub-storage-sharedvolume-spring to new Gradle format
- added mockito inline to sechub-storage-sharedvolume-spring
- downgrade flyway from 8.2.3 to 8.0.5 to be at the same level as SpringBoot
closes: #691
=> Upgrade SpringBoot to 2.6

sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go, sechub-cli/src/mercedes-benz.com/sechub/util/errorhandler.go
hint added when 401 server response
- also wording improved
- retry only for > HTTP 403
closes #281
=> Client: improve error message when api token is wrong #281

sechub-scan/src/main/java/com/daimler/sechub/domain/scan/ScanAssertService.java, sechub-schedule/src/main/java/com/daimler/sechub/domain/schedule/ScheduleAssertService.java, sechub-server/src/main/resources/application.yml
- some assert services where used by caller side but reuse them as well
- so it was not clear for the framework which one would be
initialized first.
- To avoid this, the assert services get the callers injected lazy, so
only necessary at runtime when instances are already created
This PR closes #944
=> Avoid circular reference problem on container start, fixes #944

sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/AdministrationAPIConstants.java, sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserAdministrationRestController.java, sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserEmailAddressUpdateService.java, sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/user/UserAdministrationRestControllerMockTest.java, sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/user/UserEmailAddressUpdateServiceTest.java, sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/DeveloperAdministration.java, sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/CommandUI.java, sechub-developertools/src/main/java/com/mercedesbenz/sechub/developertools/admin/ui/action/user/UpdateUserEmailAction.java, sechub-doc/src/docs/asciidoc/documents/code2doc/usecases/admin/updateUserEmailAddress.adoc, sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/UserAdministrationRestControllerRestDocTest.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AsUser.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertMail.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertUser.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/TestUserDetailInformation.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/TextSearchMode.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/MockEmailAccess.java, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/TestJSONHelper.java, sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario2/UserAdministrationScenario2IntTest.java, sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario3/ProjectAdministrationScenario3IntTest.java, sechub-notification/src/main/java/com/mercedesbenz/sechub/domain/notification/NotificationMessageHandler.java, sechub-notification/src/main/java/com/mercedesbenz/sechub/domain/notification/user/UserEmailAddressChangedNotificationService.java, sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/NotificationMessageHandlerTest.java, sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/user/UserEmailAddressChangedNotificationServiceTest.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/MessageDataKeys.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/MessageID.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/UserMessage.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/UseCaseIdentifier.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/admin/user/UseCaseAdminUpdatesUserEmailAddress.java, sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/TestCanaryException.java, sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/TestURLBuilder.java
This PR
- closes #633 
This PR is now mentioned as an example in our wiki:   
https://github.com/mercedes-benz/sechub/wiki/FAQ#is-there-a-good-example-issue-for-new-contributors
Each commit contains detailed messages about a specific work done at the commit.
The feature (#633) itself seams to be very easy to implement (at a first glance..), but implementation handled much aspects from SecHub internals:
- introduce a complete new usecase, together with documentation parts
- introduce a main logic for the feature (REST controller, gets a new method,  we create a new Service)
- automated REST documentation by dedicated *RestDocTest 
- new integration tests
- new unit tests
- domain messaging (domain `administration` sends an event which is handled by `notification` domain)
- notification …
=> Feature 633 admin can change email address of user

sechub-cli/src/mercedes-benz.com/sechub/cli/help.go
When using the cli for the first time, we copied the sample configuration from the help text into a new file.
Appearently, the json is not valid as it is presented in the help text as there is a missing comma.
=> Fix cli help text example json format

sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go, sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go
- file content is no more buffered in-memory
- now very low memory footprint
closes #933
=> file uploads are now done via io.Pipe #933

sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go, sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go, sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper_test.go, sechub-cli/src/mercedes-benz.com/sechub/testutil/ioTestHelpers.go, sechub-cli/src/mercedes-benz.com/sechub/util/fileHelpers.go
Client now sends content-length header also when uploading.
closes #1132
=> Feature 1132 client contentlength header

sechub-cli/src/mercedes-benz.com/sechub/cli/config.go, sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go, sechub-cli/src/mercedes-benz.com/sechub/cli/controller-uploadsourcezip.go, sechub-cli/src/mercedes-benz.com/sechub/cli/report.go, sechub-cli/src/mercedes-benz.com/sechub/cli/resthelper.go, sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc, sechub-doc/src/docs/asciidoc/documents/techdoc/02_security_in_development.adoc
- when debugging is enabled, log only HTTP calls but no contents
- never print SecHub report raw data to STDOUT
- docs are also updated
closes #1168
=> Introduce SECHUB_DEBUG_HTTP #1168

sechub-cli/src/mercedes-benz.com/sechub/cli/config.go, sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go, sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go, sechub-cli/src/mercedes-benz.com/sechub/cli/job.go, sechub-cli/src/mercedes-benz.com/sechub/cli/job_test.go, sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc
- client polls in increasing intervals, so results from quick backends (e.g. PDS-GoSec) are available earlier
- maximal poll interval is still the defined wait time (default: 60s)
- unit tests added
- docs + client help output updated
- code readability improved (moved progress dot printing into an extra func)
closes #1174
=> Feature 1174 client intelligent polling

sechub-cli/src/mercedes-benz.com/sechub/cli/config.go, sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go, sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go
client limit for cmdline args implemented
closes #1258
=> Client Add limit for cmdline args #1258

sechub-cli/src/mercedes-benz.com/sechub/cli/config.go, sechub-cli/src/mercedes-benz.com/sechub/cli/config_test.go, sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go, sechub-cli/src/mercedes-benz.com/sechub/cli/job.go, sechub-doc/src/docs/asciidoc/documents/code2doc/client/02_sechub_client.adoc, sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/SecHubClientExecutor.java
- made initial wait interval configurable (min. 0.1s)
- integrationtests use above setting (speedup: ~23s)
- typo fix (intervall -> interval)
- docs and unit tests updated
closes #1266
=> Feature 1266 client enable quicker tests

sechub-pds-solutions/owasp-zap/01-start-single-docker-compose.sh, sechub-pds-solutions/owasp-zap/05-start-single-sechub-network-docker-compose.sh, sechub-pds-solutions/owasp-zap/10-create-ubuntu-image.sh, sechub-pds-solutions/owasp-zap/README.adoc, sechub-pds-solutions/owasp-zap/docker-compose_pds_owasp_zap_cluster.yaml, sechub-pds-solutions/owasp-zap/docker-compose_pds_owasp_zap_cluster_object_storage.yaml, sechub-pds-solutions/owasp-zap/docker-compose_pds_owasp_zap_debian.yaml, sechub-pds-solutions/owasp-zap/docker-compose_pds_owasp_zap_debian_external_network.yaml, sechub-pds-solutions/owasp-zap/docker/Owasp-Zap-Debian.dockerfile, sechub-pds-solutions/owasp-zap/docker/zap-addons.txt, sechub-pds-solutions/owasp-zap/helm/pds-owaspzap/Chart.yaml
This PR:
-adds 2 extensions to the Owasp Zap required to use the ajax spider
-changes the base image from ubuntu to debian
-installs firefox-esr required for the ajax spider
-updates documentation and other parts from ubuntu to debian
- closes #1419 
- closes #1421
=> Fix 1419 ajaxspider no implementor

sechub-wrapper-owasp-zap/README.adoc, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/CommandLineSettings.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanConfigurationFactory.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/RuleProvider.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/data/DeactivatedRuleReferences.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/data/RuleReference.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/AbstractScan.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/util/EnvironmentVariableConstants.java, sechub-wrapper-owasp-zap/src/main/resources/full-rulesets/owasp-zap-full-ruleset-all-release-status.json, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanConfigurationFactoryTest.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/config/data/DeactivatedRuleReferencesTest.java
This PR implements:
- closes #1452
=> Wrapper OWASP ZAP can read rules to deactivate from env variable #1452

sechub-doc/src/docs/asciidoc/sechub-quickstart-guide.adoc
* Merged Ubuntu and Debian section
* Added warning for golang version #1520  
* Moved PATH variable at front #1521
closes #1520
closes #1521
=> Minor quickstart guide changes

sechub-solution/8900-helper.sh
Fixed setup_project_user_executor_profile shell function  in 8900-helper.sh #1544
closes: #1544
=> fix setup_project_user_executor_profile shell function 

sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/SchedulerRestControllerRestDocTest.java
Extend the RestDoc test to include the documentation for the `x-file-size` header.
closes: #1580
=> implement documentation for x-file-size header

sechub-solution/env-initial-sechub
Issue #1667
* Changed the double quotes to single (now bash doesn't interpret special symbols)
closes #1667
=> Bash interpreted part of the string as a variable

sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/security/AbstractAllowPDSAPISecurityConfiguration.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/configuration/AbstractAllowSecHubAPISecurityConfiguration.java
Successfully tested local scan with sechub and pds-gosec. Also verified that the header is set as expected on the sechub server and the PDS.
Alternatively we could set `default-src 'self'` instead of `default-src 'none'`.
- closes #1672
=> Set CSP header for SecHub server and PDS

sechub-developertools/scripts/sechub-api.sh
The commant `tr` is used to cut off special characters and blanks from the projectnames, after that `grep` is now used with `--line-regexp` which only outputs exact findings.
=> Added fix to sechub-api.sh script

.github/workflows/create-releases.yml, sechub-pds-solutions/checkmarx/docker/Checkmarx-Debian.dockerfile, sechub-pds-solutions/checkmarx/docker/scripts/checkmarx.sh, sechub-wrapper-checkmarx/build.gradle
All occurences of the name "sechub-pds-wrapper-checkmarx" have been changed to "sechub-wrapper-checkmarx". So there should be no more issues with incorrect names in the sha256 file.
Closes #1775
=> Feature 1775 cx sha256

sechub-pds-solutions/pds-base/docker/run.sh, sechub-pds-solutions/pds-base/env, sechub-pds-solutions/scancode/01-start-single-docker-compose.sh, sechub-pds-solutions/scancode/05-start-single-sechub-network-docker-compose.sh, sechub-pds-solutions/scancode/50-start-multiple-docker-compose.sh, sechub-pds-solutions/scancode/51-start-multiple-object-storage-docker-compose.sh, sechub-pds-solutions/scancode/docker-compose_pds_scancode.yaml, sechub-pds-solutions/scancode/docker-compose_pds_scancode_cluster.yaml, sechub-pds-solutions/scancode/docker-compose_pds_scancode_cluster_object_storage.yaml, sechub-pds-solutions/scancode/docker-compose_pds_scancode_external-network.yaml, sechub-pds-solutions/scancode/docker/Scancode-Debian.dockerfile, sechub-pds-solutions/scancode/env, sechub-pds-solutions/scancode/env-database, sechub-pds-solutions/shared/environment/env-base-image, sechub-pds-solutions/shared/scripts/9999-helper.sh
- upgrade scancode
- upgrade SPDX Tools
- enable changing the scancode version locally
- introduce env-base-image to centralize the base image version
- use env-base-image for scancode
- add PDS_VERSION to PDS output
closes: #1863
=> Upgrade Scancode and dependencies #1863

sechub-pds-solutions/pds-base/10-create-image.sh
- now prints usage
- PDS_VERSION is now mandatory script parameter
- usage docs improved
closes #1998
=> create image script improved #1998

sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/api/AssertReport.java, sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario20/PDSSecretScanJobScenario20IntTest.java, sechub-scan-product-sereco/src/main/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoProductResultTransformer.java, sechub-scan-product-sereco/src/test/java/com/mercedesbenz/sechub/domain/scan/product/sereco/SerecoProductResultTransformerTest.java
=> Fix problem of missing code call hierarchy in reports for scan type `secretScan`

sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/resolve/TargetResolverService.java
Because of a missing space, the example with the pipe symbol was not rendered with highlighting.
=> Improved documentation generation output #2018

build.gradle, gradle/build-maven.gradle
Added CyclonDx Gradle plugin for automated SBOM generation. SBOM includes only runtime dependencies.
Usage: `./gradlew cyclonedxBom`
closes: #1995
=> feature 1995 - cyclonDX sbom generation

.github/workflows/create-pds-tools-release.yml, .github/workflows/create-releases.yml, .github/workflows/release-owaspzap-wrapper.yml
- To enable testing the zap wrapper release job on github. Functionality comes with a separate PR.
- Consistent naming pattern (PDS-Tools)
- whitespace changes
=> add new action to build owasp zap wrapper into develop branch #1616

sechub-developertools/scripts/sechub-api.sh
Enhanced `sechub-api.sh` so that the actions
- `executor_details`
- `executor_delete`
- `executor_update`
also accept executor names.
closes #2149
=> sechub-api.sh: enable use of executor names #2149

sechub-pds-solutions/owasp-zap/docker/pds-config.json, sechub-pds-solutions/owasp-zap/docker/scripts/owasp-zap.sh, sechub-wrapper-owasp-zap/README.adoc, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/CommandLineSettings.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/OwaspZapScanExecutor.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContext.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContextFactory.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/UnauthenticatedScan.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/scan/auth/AbstractAuthScan.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/owaspzapwrapper/util/TargetConnectionChecker.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/cli/OwaspZapScanExecutorTest.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/config/OwaspZapScanContextFactoryTest.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/owaspzapwrapper/util/TargetConnectionCheckerTest.java
- made connection check configurable (added ability to turn it on/off with an executor parameter)
- added the parameter to the PDS_OWASPZAP
- extended the user message when the ZAP sites tree is empty after crawling phase. This is important since we will not perform the initial connection check on default in the future.
- improved connection check logic in case it will be used in the future. We only consider http response codes as failure if we are sure something went wrong on the connection attempts (http 404 or 5xx)
- in pds-config.json updated minutesToWaitForProductResult to 600 to be the largest value, larger than on the executors
- closes #2201
=> Feature 2201 improve inital target connection check and make it configurable

sechub-solution/docker/SecHub-Alpine.dockerfile, sechub-solution/docker/SecHub-Debian.dockerfile, sechub-solution/docker/SecHub-Fedora.dockerfile, sechub-solution/docker/SecHub-Rocky.dockerfile
- added labels according to the opencontainers/image-spec
- labels added to: Alpine, Debian, Fedora and Rocky images
closes: #2233
=> Add labels to the SecHub dockerfiles #2233

sechub-developertools/scripts/sechub-api.sh
Now both: userID or email address can be specified in `user_details` call.
closes #2274
=> sechub-api.sh: user search by email #2274

README.adoc
The status of the SecretScanner is not experimental anymore. That's why it needs to be changed to "productive".
Closes #2364
=> Changed sesc status to productive

sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/adopt/AdoptedSystemTestDefaultFallback.java, sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/config/DefaultFallback.java, sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/config/ProjectDefinition.java, sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/config/SystemTestConfigurationBuilder.java, sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/config/SystemTestRuntimeLocalSecHubProductConfigurator.java, sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/init/SystemTestRuntimePreparator.java, sechub-systemtest/src/main/java/com/mercedesbenz/sechub/systemtest/runtime/launch/SystemTestRuntimeProductLauncher.java, sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/SystemTestDryRunTest.java, sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/SystemTestFrameworkIntTest.java
=> Implemented whitelist handling for systemtests #2534

sechub-doc/src/docs/asciidoc/sechub-getting-started.adoc
* The script that sets up a Sechub(`sechub-solution/setup-pds/setup-gosec.sh`) project requires `jq` to properly display information
closes #2743
=> Added jq as requirement

sechub-pds-solutions/owaspzap/docker/Owasp-Zap-Debian.dockerfile, sechub-pds-solutions/owaspzap/env
- updated ZAP wrapper version in configs
- closes #2792
=> Release ZAP Wrapper 1.5.0 #2792

.github/workflows/release-client-server-pds.yml, buildSrc/src/main/groovy/VersionData.groovy, gradle/build-versioning.gradle, sechub-doc/build.gradle
- Actions workflow now fetches git tag history so latest versions can be obtained for documentation versioning
- Extended the `VersionData` Groovy class so the versions for docs can also be stored
- Added the same to the Gradle files
- Tested successfully with `./gradlew documentation-with-pages`
- closes #2798
=> Proper docs versioning in build + release job  #2798

sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/cli/ZapWrapperExitCode.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
- closes #2811 
- fix order to load client certificate before openApi definitions
- improve error handling if the client certificate file was not extracted correctly
- update test cases to match improved error handling
=> Fix ZAP configuration order #2811

sechub.json
- exclude SecHub reports
- exclude mock data
- exclude go library code
- added scanning for secrets
- closes #2923
=> scan config improved #2923

.github/workflows/gradle.yml
- also removed documentation branch because it exists no more
- closes #2957
=> no builds for gha_ branches #2957

gradle/build-versioning.gradle
- now for all relevant modules, the latest tag is retrieved
- this fixes the failing release build workflow
- closes #2972
=> fix build versioning #2972

sechub-adapter-pds/src/main/java/com/mercedesbenz/sechub/adapter/pds/PDSSecretScanConfigImpl.java
Rename PDSSecretScanConfigImpl's PDSLicenseScanConfigBuilder static class to PDSSecretScanConfigBuilder #2933
- closes #2933
=> Rename PDSSecretScanConfigImpl's PDSLicenseScanConfigBuilder static class to PDSSecretScanConfigBuilder 

sechub-cli/src/mercedes-benz.com/sechub/cli/config.go, sechub-cli/src/mercedes-benz.com/sechub/cli/constants.go, sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig.go, sechub-cli/src/mercedes-benz.com/sechub/cli/sechubconfig_test.go, sechub-doc/src/docs/asciidoc/documents/client/02_sechub_client.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example12_secret_scan_with_sources_data_reference.json, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example14_secret_scan_and_code_scan_with_sources_data_reference.json
- option `-addScmHistory`
- env var `SECHUB_ADD_SCM_HISTORY`
- unit test
- closes #3079
=> Client: new option for uploading SCM history #3079

sechub-commons-model/src/main/java/com/mercedesbenz/sechub/commons/model/SecHubWebScanApiConfiguration.java, sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubWebScanApiConfigurationTest.java, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config.adoc, sechub-doc/src/docs/asciidoc/documents/shared/configuration/sechub_config_example8_web_scan_openapi_with_data_reference.json, sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/SchedulerRestControllerRestDocTest.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/internal/scan/ClientApiFacade.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java, sechub-wrapper-owasp-zap/src/test/resources/sechub-config-examples/no-auth-with-openapi-from-file-and-url.json, sechub-wrapper-owasp-zap/src/test/resources/sechub-config-examples/no-auth-with-openapi-from-url.json
=> Feature 1436 load api defintion from url

sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/AsciidocGenerator.java, sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/PDSStartupAssertEnvironmentVariablesUsed.java, sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/security/PDSSecurityConfiguration.java, sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java, sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSSharedVolumePropertiesSetup.java, sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/PDSStartupAssertEnvironmentVariablesUsedTest.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/SharedVolumePropertiesSetup.java
=> Fixed documentation build by providing correct fallback objects #3257

.github/workflows/release-github-action.yml
- closes #3564 
- Also made GHACTION a global environment variable
=> provide path to git add #3564

sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/helper/ZapProductMessageHelper.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/internal/scan/ClientApiFacade.java, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScanner.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/helper/ZapProductMessageHelperTest.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/scan/ZapScannerTest.java
- closes #3507 
- closes #3511
=> Feature 3507 introduce x sechub dast header

gradle/libraries.gradle, sechub-wrapper-owasp-zap/build.gradle, sechub-wrapper-owasp-zap/src/main/java/com/mercedesbenz/sechub/zapwrapper/util/TOTPGenerator.java, sechub-wrapper-owasp-zap/src/test/java/com/mercedesbenz/sechub/zapwrapper/util/TOTPGeneratorTest.java
=> Implement TOTP generation #3526

gradle/build-versioning.gradle, sechub-cli/build_go.sh
- closes #3641 
Related information: see https://hackernoon.com/building-reproducible-verifiable-binaries-with-golang
--> "There is no built-in way to compile a reproducible binary with Golang."
Anyhow with the applied changes, now the build is reproducible on the same platform (Linux) with the same Go version (go version go1.21.6 linux/amd64) across different machines:
- Developer Laptop running Ubuntu
- local VM running Debian
- two different cloud VMs running Debian (different CPUs)
Also the build is now agnostic of build pathes.
(Builds in different directories produce the same sha256 checksums.)
=> Feature 3641 make client builds reproducible #3641

README.adoc, sechub-doc/src/docs/asciidoc/documents/techdoc/05_build.adoc, sechub-website/components/home/Hero.vue
Also improved wording in SecHub's introduction
- closes #3433
=> documented dev tagging for published artifacts #3433

sechub-doc/src/main/java/com/mercedesbenz/sechub/docgen/util/DocGeneratorUtil.java, sechub-doc/src/test/java/com/mercedesbenz/sechub/docgen/util/DocGenUtilTest.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/UseCaseRestDoc.java
This PR 
- closes #3647 
- closes #3652
=> Improve documentation output for REST doc + fix scope calculation

sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/AdministrationAPIConstants.java, sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/job/JobCancelService.java, sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/job/JobRestController.java, sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/job/JobCancelServiceTest.java, sechub-api-java/src/main/resources/reduced-openapi3.json, sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/JobRestControllerRestDocTest.java, sechub-openapi-java/src/main/resources/openapi.yaml, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/error/InternalServerErrorException.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/APIConstants.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/security/SecHubSecurityConfiguration.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/UseCaseIdentifier.java, sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/usecases/job/UseCaseUserCancelsJob.java, sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/SecHubTestURLBuilder.java
=> Feature 3789 user can cancel job

sechub-pds-solutions/owaspzap/env
A new owasp zap wrapper was released, therefore the env file had to be updated accordingly.
=> Updated OWASP ZAP wrapper version

sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/shutdown/SpringApplicationShutdownHandler.java
This is a follow up issue from PR #3918 - changed the log error message
=> Rename shutdown listener log message on runtime exceptions

sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario1/TemplateScenario1IntTest.java, sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/template/TemplateRepository.java, sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/template/TemplateService.java, sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/template/TemplateRepositoryDBTest.java, sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/template/TemplateServiceTest.java
=> respond with 404 if template not found on deletion #3784

sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario1/AssetScenario1IntTest.java, sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/asset/AssetFileRepository.java, sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/asset/AssetService.java, sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/asset/AssetFileRepositoryDBTest.java, sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/asset/AssetServiceTest.java
=> respond with 404 if asset or asset file not found on deletion #3783
